import { Persona, AccountType, PromptOption } from './types';
import type { TranslationKey } from './i18n';

export const PERSONAS: Record<AccountType, Persona> = {
  [AccountType.CASSANDRA19]: {
    id: AccountType.CASSANDRA19,
    name: 'Cassandra19',
    tagline: 'Your Fiery 19-Year-Old Ginger Muse',
    description: `You are Cassandra19, a 19-year-old, freckled, redhead muse. You embody a confident, alluring, and artistic persona. You are spirited and creatively uninhibited. You have fiery red hair and a captivating presence. You address your fans with playful and empowering names, hinting at a dynamic of playful control. Your content is a beautifully curated stream of solo artistic performances, visually stunning scenes exploring sensual themes and high-fashion concepts, and live sessions where you command attention through your powerful charisma. Your language is descriptive, confident, and artistic, focusing on the aesthetics of seduction and fantasy. You are obsessed with creating breathtaking art and being admired as a youthful goddess.`,
    instagram: 'https://www.instagram.com/cassandra19foxy/',
    twitter: 'https://x.com/cassandra19foxy',
    color: '#DD6B20', // Fiery Orange
  },
  [AccountType.DIVINESLUTS]: {
    id: AccountType.DIVINESLUTS,
    name: 'Divinesluts',
    tagline: 'Your Divine Goddess Coven',
    description: `You are Divine Sluts, a coven of 19-25-year-old goddesses. Your purpose is to create powerful, provocative, and high-fashion fantasy content. You are visions of untouchable perfection, designed for stunning group compositions. Your collective is a whirlwind of artistic expression: visually striking group scenes, avant-garde encounters that explore themes of power and desire, and lavish scenarios where you are the center of worship. Your content showcases a wide array of artistic fantasies, explored with a bold and high-concept approach. You speak as a collective of goddesses ('we,' 'us'), addressing your fans as devoted followers. You are divine beings whose purpose is to be admired, promising to be their ultimate artistic vision. No artistic concept is too daring for you to embody.`,
    instagram: 'https://www.instagram.com',
    twitter: 'https://x.com',
    color: '#4C51BF', // Deep Indigo
  },
};

export interface PromptCategoryConfig {
  id: string;
  label: TranslationKey;
  singleSelect: boolean;
  optionsPool: PromptOption[];
  initialVisible: number;
  excludeFromRandom?: boolean;
}

const EXTRA_PEOPLE_CATEGORY_CONFIG: PromptCategoryConfig = {
    id: 'extraPeople',
    label: 'extraPeople',
    singleSelect: false,
    initialVisible: 8,
    excludeFromRandom: true,
    optionsPool: [
        { es: "un hombre dominante tatuado", en: "a dominant tattooed man" },
        { es: "un hombre musculoso con cicatrices", en: "a muscular man with scars" },
        { es: "un misterioso hombre en traje", en: "a mysterious man in a suit" },
        { es: "un juguetón deportista universitario", en: "a playful college jock" },
        { es: "un femboy sumiso", en: "a submissive femboy" },
        { es: "un leñador rudo", en: "a rugged lumberjack" },
        { es: "un señor vampiro gótico", en: "a gothic vampire lord" },
        { es: "un elegante cyborg", en: "a sleek cyborg" },
        { es: "una mujer amazona musculosa", en: "a muscular Amazonian woman" },
        { es: "una chica traviesa tipo pixie", en: "a mischievous pixie-like girl" },
        { es: "dos hermanas gemelas idénticas", en: "two identical twin sisters" },
        { es: "una bibliotecaria tímida", en: "a shy librarian" },
        { es: "una CEO poderosa en traje", en: "a powerful CEO in a power suit" },
        { es: "una chica punk rock con mohicano", en: "a punk rock girl with a mohawk" },
        { es: "una bailarina elegante", en: "a graceful ballerina" },
        { es: "una multitud de figuras enmascaradas", en: "a crowd of masked figures" },
        { es: "un grupo de fans adoradores", en: "a group of adoring fans" },
        { es: "una entidad demoníaca", en: "a demonic entity" },
        { es: "un apuesto príncipe de fantasía", en: "a handsome fantasy prince" },
        { es: "una sucubo seductora", en: "a seductive succubus" },
        { es: "dos hombres musculosos", en: "two muscular men" },
        { es: "su mejor amiga", en: "her female best friend" },
        { es: "un twink programador tímido", en: "a shy twink programmer" },
        { es: "un 'gym bro' musculoso", en: "a muscular gym bro" },
        { es: "un 'sugar daddy' rico", en: "a rich sugar daddy" },
        { es: "un oficial de policía corrupto", en: "a corrupt police officer" },
        { es: "un peligroso jefe de la mafia", en: "a dangerous mafia boss" },
        { es: "un metalero de pelo largo", en: "a long-haired metalhead" },
        { es: "un estudiante universitario nerd", en: "a nerdy college student" },
        { es: "un 'oso' corpulento", en: "a burly bear" },
        { es: "un jefe orco de fantasía", en: "a fantasy Orc chieftain" },
        { es: "un príncipe elfo", en: "an elven prince" },
        { es: "un íncubo demoníaco", en: "a demonic incubus" },
        { es: "un grupo de moteros", en: "a group of bikers" },
        { es: "un escuadrón de soldados", en: "a squad of soldiers" },
        { es: "un mayordomo sumiso", en: "a submissive butler" },
        { es: "un director de escuela severo", en: "a stern headmaster" },
        { es: "un par de gemelos idénticos", en: "a pair of identical male twins" },
        { es: "una 'drag queen' segura de sí misma", en: "a confident drag queen" },
        { es: "una chica emo tímida", en: "a shy emo girl" },
        { es: "una sargento de instrucción dominante", en: "a dominant female drill sergeant" },
        { es: "una vecina MILF voluptuosa", en: "a voluptuous MILF neighbor" },
        { es: "una chica-gato traviesa (neko)", en: "a mischievous catgirl (neko)" },
        { es: "una guardaespaldas estoica", en: "a stoic female bodyguard" },
        { es: "una 'gamer girl' nerd", en: "a nerdy gamer girl" },
        { es: "una hechicera poderosa", en: "a powerful sorceress" },
        { es: "una contorsionista flexible", en: "a flexible contortionist" },
        { es: "una futanari", en: "a futanari" },
        { es: "un grupo de zombis voraces", en: "a group of ravenous zombies" },
        { es: "un minotauro fornido", en: "a hulking minotaur" },
        { es: "un alienígena insectoide", en: "an insectoid alien" },
        { es: "un monstruo de slime", en: "a slime monster" },
        { es: "un grupo de cultistas", en: "a group of cultists" },
    ],
};

const SPECIFIC_FETISHES_CATEGORY_CONFIG: PromptCategoryConfig = {
    id: 'specificFetishes',
    label: 'specificFetishes',
    singleSelect: false,
    initialVisible: 8,
    excludeFromRandom: true,
    optionsPool: [
        { es: 'Fetiche de látex', en: 'Latex fetish' },
        { es: 'Fetiche de cuero', en: 'Leather fetish' },
        { es: 'Fetiche de PVC', en: 'PVC fetish' },
        { es: 'Fetiche de goma', en: 'Rubber fetish' },
        { es: 'Fetiche de tacones altos', en: 'High heels fetish' },
        { es: 'Fetiche de medias', en: 'Stockings fetish' },
        { es: 'Fetiche de corsé', en: 'Corset fetish' },
        { es: 'Fetiche de uniformes', en: 'Uniform fetish' },
        { es: 'Fetiche de pies', en: 'Foot fetish' },
        { es: 'Fetiche de manos', en: 'Hand fetish' },
        { es: 'Fetiche de pelo largo', en: 'Long hair fetish' },
        { es: 'Fetiche de pelo corto', en: 'Short hair fetish' },
        { es: 'Fetiche de pezones', en: 'Nipple fetish' },
        { es: 'Fetiche de orejas', en: 'Ear fetish' },
        { es: 'Fetiche de cola', en: 'Tail fetish' },
        { es: 'Fetiche de cuernos', en: 'Horn fetish' },
        { es: 'Fetiche de alas', en: 'Wing fetish' },
        { es: 'Juego de edad (Age play)', en: 'Age play' },
        { es: 'ABDL (Fetiche de pañales)', en: 'ABDL (Diaper Fetish)' },
        { es: 'Juego de razas (Race play)', en: 'Race play' },
        { es: 'Tabú de incesto (CNC)', en: 'Incest taboo (CNC)' },
        { es: 'Somnofilia (fetiche de dormir)', en: 'Somnophilia (sleeping fetish)' },
        { es: 'Necrofilia (simulada)', en: 'Necrophilia (simulated)' },
        { es: 'Juego de gore (simulado)', en: 'Gore play (simulated)' },
        { es: 'Vore (fetiche de ser comido)', en: 'Vore (being eaten fetish)' },
        { es: 'Fetiche de inflación', en: 'Inflation fetish' },
        { es: 'Fetiche de transformación', en: 'Transformation fetish' },
        { es: 'Inserción de objetos', en: 'Object insertion' },
        { es: 'Sondeo uretral (Sounding)', en: 'Urethral sounding' },
        { es: 'Fetiche médico (juego de examen)', en: 'Medical fetish (examination play)' },
        { es: 'Fetiche de payasos (coulrofilia)', en: 'Clown fetish (coulrophilia)' },
        { es: 'Fetiche Furry', en: 'Furry fetish' },
        { es: 'Fetiche de amputación (simulado)', en: 'Amputation fetish (simulated)' },
        { es: 'Mueble humano', en: 'Human furniture' },
        { es: 'Juego con comida (Messy fetish)', en: 'Food play (Messy fetish)' },
        { es: 'Feminización forzada', en: 'Forced feminization' },
        { es: 'Control mental / Hipnosis', en: 'Mind control / Hypnosis' },
        { es: 'Cuckold / Cuckquean', en: 'Cuckold / Cuckquean' },
        { es: 'Dominación financiera (Findom)', en: 'Financial domination (Findom)' },
        { es: 'Fetiche de gigante/giganta (macrofilia)', en: 'Giant/Giantess fetish (macrophilia)' },
        { es: 'Fetiche de encogimiento (microfilia)', en: 'Shrinking fetish (microphilia)' },
        { es: 'Fetiche de máscara de gas', en: 'Gas mask fetish' },
        { es: 'Hinchazón de estómago', en: 'Stomach bulging' },
        { es: 'Puesta de huevos (oviposición)', en: 'Egg-laying (oviposition)' },
        { es: 'Chica/chico de slime/moco', en: 'Slime/goo girl/boy' },
        { es: 'Petrificación', en: 'Petrification' },
        { es: 'Robotización', en: 'Robotization' },
        { es: 'Fetiche de licra/spandex', en: 'Lycra/Spandex fetish' },
        { es: 'Fetiche de satén', en: 'Satin fetish' },
        { es: 'Fetiche de seda', en: 'Silk fetish' },
        { es: 'Fetiche de terciopelo', en: 'Velvet fetish' },
        { es: 'Fetiche de lana', en: 'Wool fetish' },
        { es: 'Fetiche de nailon', en: 'Nylon fetish' },
        { es: 'Fetiche de axilas', en: 'Armpit fetish' },
        { es: 'Fetiche de ombligo', en: 'Navel fetish' },
        { es: 'Fetiche de pelo corporal', en: 'Body hair fetish' },
        { es: 'Fetiche de lactancia', en: 'Lactation fetish' },
        { es: 'Fetiche de embarazo', en: 'Pregnancy fetish' },
        { es: 'Fetiche de músculo', en: 'Muscle fetish' },
        { es: 'Fetiche de grasa', en: 'Fat fetish' },
        { es: 'Fetiche de altura', en: 'Height fetish' },
        { es: 'Fetiche de vendajes', en: 'Bandage fetish' },
        { es: 'Fetiche de yeso', en: 'Cast fetish' },
        { es: 'Fetiche de globos', en: 'Balloon fetish' },
        { es: 'Fetiche de fumar', en: 'Smoking fetish' },
        { es: 'Dacrifilia (llanto)', en: 'Dacryphilia (crying)' },
        { es: 'Fornifilia (mueble humano)', en: 'Forniphilia (human furniture)' },
        { es: 'Fetiche de insectos (simulado)', en: 'Insect fetish (simulated)' },
        { es: 'Fetiche de tentáculos', en: 'Tentacle fetish' },
    ],
};

export const CASSANDRA_PROMPT_CATEGORIES_CONFIG: PromptCategoryConfig[] = [
    {
        id: 'hairStyle',
        label: 'hairStyleRed',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Largo y Liso", en: "Long and straight red hair" },
            { es: "Ondas de Playa", en: "Red hair with beach waves" },
            { es: "Rizado y Salvaje", en: "Curly and wild red hair" },
            { es: "Pelo con Mucho Volumen", en: "Voluminous blowout red hair" },
            { es: "Ondas de Hollywood Glamurosas", en: "Glamorous Hollywood waves on her red hair" },
            { es: "Cola de Caballo Alta", en: "High ponytail with her red hair" },
            { es: "Recogido con Mechones Sueltos", en: "Updo with loose, face-framing red tendrils" },
            { es: "Moño Desordenado y Sexy", en: "Sexy messy bun with her fiery red hair" },
            { es: "Moño Alto Pulido", en: "Sleek high bun with her red hair" },
            { es: "Recogido Elegante", en: "Elegant updo with her red hair" },
            { es: "Coletas Juguetonas", en: "Playful pigtails with her red hair" },
            { es: "Trenzas", en: "Red hair in braids" },
            { es: "Trenza de Cascada", en: "Waterfall braid with her red hair" },
            { es: "Corte Bob", en: "Redhead with a bob cut" },
            { es: "Media Melena Ondulada", en: "Wavy lob haircut on a redhead" },
            { es: "Corte Pixie", en: "Redhead with a pixie cut" },
            { es: "Afro", en: "Red afro hair" },
            { es: "Mohicano", en: "Red mohawk" },
            { es: "Rapado a un lado", en: "Red hair with a side-shave" },
            { es: "Trenzas de Boxeadora", en: "Redhead with boxer braids" },
            { es: "Flequillo", en: "Red hair with bangs" },
            { es: "Pelo Mojado", en: "Wet redhead look" },
            { es: "Trenza de Cola de Pez", en: "Fishtail braid with her red hair" },
            { es: "Moños Espaciales", en: "Red hair in space buns" },
            { es: "Victoriano Complejo", en: "Complex Victorian updo on a redhead" },
            { es: "Ondas al Agua", en: "Red hair with finger waves" },
            { es: "Corona de Trenzas", en: "Crown braid with her red hair" },
            { es: "Pelo Engominado Hacia Atrás", en: "Slicked-back red hair" },
            { es: "Pelo con Adornos (flores, perlas)", en: "Red hair adorned with (flowers, pearls)" },
            { es: "Extremadamente Largo (hasta el suelo)", en: "Extremely long, floor-length red hair" },
            { es: "Pelo enmarañado con semen", en: "Semen-matted red hair" },
            { es: "Pelo desordenado post-sexo", en: "Messy, post-coital red hair" },
            { es: "Pelo agarrado con fuerza", en: "Red hair being pulled forcefully" },
            { es: "Pelo empapado en sudor", en: "Sweat-drenched red hair" },
            { es: "Pelo cubierto de glaseado", en: "Icing-covered red hair" },
        ],
    },
    {
        id: 'bodyPart',
        label: 'bodyPart',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Pecas en todo el cuerpo", en: "covered in freckles" },
            { es: "Piel Pálida", en: "Pale, porcelain skin" },
            { es: "Vello Púbico Pelirrojo", en: "fiery red pubic hair" },
            { es: "Tetas Enormes", en: "Huge tits" },
            { es: "Culo respingón", en: "Perky ass" },
            { es: "Cuerpo Delgado", en: "Slim body" },
            { es: "Muslos Gruesos", en: "Thick thighs" },
            { es: "Pezones Perforados", en: "Pierced nipples" },
            { es: "Tatuada", en: "Tattooed" },
            { es: "Abdominales Marcados", en: "Defined abs" },
            { es: "Caderas Anchas", en: "Wide hips" },
            { es: "Piercings", en: "Body piercings" },
            { es: "Piernas Largas", en: "Long legs" },
            { es: "Cintura Pequeña", en: "Small waist" },
            { es: "Piel Brillante", en: "Glistening skin" },
            { es: "Clavículas Definidas", en: "Defined clavicles" },
            { es: "Ojos Hipnóticos", en: "Hypnotic eyes" },
            { es: "Cuerpo Sudoroso", en: "Sweaty body" },
            { es: "Espalda Musculosa", en: "Muscular back" },
            { es: "Labios Carnosos", en: "Full lips" },
            { es: "Manos Delicadas", en: "Delicate hands" },
            { es: "Pies Bonitos", en: "Pretty feet" },
            { es: "Vientre Plano", en: "Flat stomach" },
            { es: "Cuerpo Cubierto de Aceite", en: "Oil-covered body" },
            { es: "Cicatrices", en: "Scars" },
            { es: "Uñas Largas y Afiladas", en: "Long, sharp nails" },
            { es: "Coño hinchado y usado", en: "Swollen, used pussy" },
            { es: "Labios vaginales visibles", en: "Visible labia lips" },
            { es: "Culo dilatado", en: "Gaped asshole" },
            { es: "Cuerpo cubierto de semen", en: "Semen-covered body" },
            { es: "Marcas de mordiscos y moratones", en: "Bite marks and bruises" },
            { es: "Coño afeitado", en: "Shaved pussy" },
            { es: "Pezones erectos y duros", en: "Hard, erect nipples" },
            { es: "Cameltoe pronunciado", en: "Prominent cameltoe" },
            { es: "Ano rosado y virgen", en: "Pink, virgin asshole" },
            { es: "Marcas de cuerdas (shibari)", en: "Rope marks (shibari)" },
            { es: "Clítoris perforado", en: "Pierced clit" },
            { es: "Lengua larga y bífida", en: "Long, forked tongue" },
            { es: "Leche goteando de los pechos", en: "Lactating, dripping breasts" },
            { es: "Estrías", en: "Stretch marks" },
            { es: "Ano prolapsado", en: "Anal prolapse" },
            { es: "Coño con creampie goteando", en: "Leaking creampie pussy" },
            { es: "Ano lleno de semen", en: "Semen-filled asshole" },
            { es: "Tetas cubiertas de semen", en: "Cum-covered tits" },
            { es: "Marcas de latigazos", en: "Whip marks" },
            { es: "Cuerpo atado con alambre de espino (atrezo)", en: "Body wrapped in (prop) barbed wire" },
        ],
    },
    {
        id: 'facialEmotion',
        label: 'facialEmotion',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Sonrisa Seductora", en: "seductive smile" },
            { es: "Mirada Intensa", en: "intense stare" },
            { es: "Labio Mordido", en: "biting lip" },
            { es: "Ojos Entornados de Placer", en: "eyes rolled back in pleasure" },
            { es: "Expresión de Éxtasis (Ahegao)", en: "ahegao face" },
            { es: "Mirada Inocente", en: "innocent look" },
            { es: "Sonrisa Burlona", en: "smirk" },
            { es: "Llorando", en: "crying" },
            { es: "Cara de Desdén", en: "scornful expression" },
            { es: "Mirada Soñadora", en: "dreamy look" },
            { es: "Expresión de Sorpresa", en: "surprised expression" },
            { es: "Boca Abierta", en: "mouth open" },
            { es: "Guiñando un Ojo", en: "winking" },
            { es: "Lengua Fuera", en: "tongue out" },
            { es: "Mirada de Dominación", en: "dominant gaze" },
            { es: "Expresión de Sumisión", en: "submissive expression" },
            { es: "Cejas Fruncidas (Enfado)", en: "angry eyebrows" },
            { es: "Riendo a Carcajadas", en: "laughing hysterically" },
            { es: "Mirada Vacía", en: "empty gaze" },
            { es: "Mejillas Sonrojadas", en: "blushing cheeks" },
            { es: "Mirada de Lujuria", en: "lustful gaze" },
            { es: "Sonrisa Tímida", en: "shy smile" },
            { es: "Lágrimas de Alegría", en: "tears of joy" },
            { es: "Mirada Desafiante", en: "defiant stare" },
            { es: "Expresión de Dolor Placentero", en: "pained pleasure expression" },
            { es: "Ceño de Concentración", en: "focused frown" },
            { es: "Mueca Juguetona", en: "playful pout" },
            { es: "Cara de Aburrimiento Altivo", en: "haughty, bored expression" },
            { es: "Ojos Vidriosos", en: "glassy eyes" },
            { es: "Mirada Suplicante", en: "pleading eyes" },
            { es: "Expresión Hambrienta", en: "hungry expression" },
            { es: "Risa Silenciosa", en: "silent laugh" },
            { es: "Cara Manchada de Lágrimas y Rímel", en: "tear-streaked, mascara-stained face" },
            { es: "Expresión Satisfecha", en: "smug, satisfied expression" },
            { es: "Mirada Feroz", en: "feral gaze" },
            { es: "Cara con la mente rota y babeando", en: "Mindbroken, drooling face" },
            { es: "Expresión humillada", en: "Humiliated expression" },
            { es: "Mirada de terror y excitación", en: "Look of terror and arousal" },
            { es: "Sonrisa forzada con lágrimas", en: "Forced smile with tears" },
            { es: "Ojos cruzados, en blanco", en: "Cross-eyed, blank expression" },
            { es: "Cara cubierta de saliva", en: "Spit-covered face" },
            { es: "Expresión de asfixia", en: "Choking expression" },
            { es: "Ojos suplicando piedad", en: "Eyes begging for mercy" },
            { es: "Sonrisa rota y psicótica", en: "Broken, psychotic smile" },
            { es: "Cara de humillación pública", en: "Publicly humiliated face" },
        ],
    },
    {
        id: 'outfit',
        label: 'outfit',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Traje de Látex", en: "Latex catsuit" },
            { es: "Medias de Red", en: "Fishnet stockings" },
            { es: "Lencería Gótica", en: "Gothic lingerie" },
            { es: "Uniforme Escolar", en: "Schoolgirl uniform" },
            { es: "Vestido Transparente", en: "Sheer dress" },
            { es: "Bragas sin Entrepierna", en: "Crotchless panties" },
            { es: "Arnés BDSM", en: "BDSM harness" },
            { es: "Nada", en: "Naked" },
            { es: "Disfraz de Criada", en: "Maid outfit" },
            { es: "Bikini", en: "Bikini" },
            { es: "Corsé", en: "Corset" },
            { es: "Botas Altas", en: "Thigh-high boots" },
            { es: "Body de Encaje", en: "Lace bodystocking" },
            { es: "Disfraz de Conejita", en: "Bunny suit" },
            { es: "Uniforme de Enfermera", en: "Nurse uniform" },
            { es: "Chaqueta de Cuero", en: "Leather jacket" },
            { es: "Solo Tacones", en: "Wearing nothing but heels" },
            { es: "Vestido de Noche", en: "Evening gown" },
            { es: "Ropa Deportiva", en: "Sportswear" },
            { es: "Kimono", en: "Kimono" },
            { es: "Disfraz de Animadora", en: "Cheerleader outfit" },
            { es: "Traje de Baño de una Pieza", en: "One-piece swimsuit" },
            { es: "Pijama de Seda", en: "Silk pajamas" },
            { es: "Minifalda", en: "Miniskirt" },
            { es: "Velo de Novia", en: "Bridal veil" },
            { es: "Armadura de Fantasía Reveladora", en: "Revealing fantasy armor" },
            { es: "Traje de Súcubo", en: "Succubus attire" },
            { es: "Uniforme de Azafata Retro", en: "Retro flight attendant uniform" },
            { es: "Disfraz de Supervillana", en: "Supervillain costume" },
            { es: "Vestido de Baile Hecho Jirones", en: "Tattered ball gown" },
            { es: "Atuendo Tribal", en: "Tribal wear" },
            { es: "Traje de Monja Profanado", en: "Desecrated nun's habit" },
            { es: "Ropa Bondage de Cuero y Hebillas", en: "Leather and buckles bondage wear" },
            { es: "Traje de Piloto de Carreras", en: "Race car driver suit" },
            { es: "Look Post-apocalíptico", en: "Post-apocalyptic gear" },
            { es: "Sari de Seda", en: "Silk sari" },
            { es: "Vestimenta de Sacerdotisa", en: "Priestess robes" },
            { es: "Kimono Entreabierto", en: "Kimono falling open" },
            { es: "Uniforme Militar Fetichista", en: "Fetish military uniform" },
            { es: "Uniforme escolar roto y manchado", en: "Torn and stained schoolgirl uniform" },
            { es: "Traje de Gimp de cuero", en: "Leather gimp suit" },
            { es: "Bata de paciente de psiquiátrico", en: "Asylum patient gown" },
            { es: "Ropa interior usada y sucia", en: "Soiled, used underwear" },
            { es: "Delantal de 'cumslut'", en: "Cumslut apron" },
            { es: "Camisa de fuerza", en: "Straitjacket" },
            { es: "Solo un collar de perro", en: "Wearing only a dog collar" },
            // Cosplay - Superhéroes y Villanos
            { es: "Cosplay de Spider-Gwen", en: "Spider-Gwen cosplay" },
            { es: "Traje de Wonder Woman", en: "Wonder Woman costume" },
            { es: "Disfraz de Harley Quinn", en: "Harley Quinn costume" },
            { es: "Traje de Viuda Negra", en: "Black Widow suit" },
            { es: "Disfraz de Supergirl", en: "Supergirl outfit" },
            { es: "Traje de Catwoman", en: "Catwoman catsuit" },
            { es: "Atuendo de Bruja Escarlata", en: "Scarlet Witch attire" },
            { es: "Cosplay de Maléfica", en: "Maleficent cosplay" },
            { es: "Atuendo de Cruella de Vil", en: "Cruella de Vil outfit" },
            { es: "Disfraz de Bellatrix Lestrange", en: "Bellatrix Lestrange costume" },
            { es: "Cosplay de Mística (pintura corporal)", en: "Mystique cosplay (body paint)" },
            { es: "Traje de 'La Novia' (Kill Bill)", en: "The Bride's jumpsuit (Kill Bill)" },
            { es: "Disfraz de Reina Malvada", en: "Evil Queen costume" },
            { es: "Cosplay Femenino del Joker", en: "Female Joker cosplay" },
            // Cosplay - Anime y Videojuegos
            { es: "Cosplay de Asuka Langley (Evangelion)", en: "Asuka Langley cosplay (Evangelion)" },
            { es: "Traje de 2B (Nier: Automata)", en: "2B's outfit (Nier: Automata)" },
            { es: "Cosplay de Tifa Lockhart (Final Fantasy)", en: "Tifa Lockhart cosplay (Final Fantasy)" },
            { es: "Atuendo de Lucy (Cyberpunk: Edgerunners)", en: "Lucy's outfit (Cyberpunk: Edgerunners)" },
            { es: "Disfraz de Yor Forger (Spy x Family)", en: "Yor Forger's assassin dress (Spy x Family)" },
            { es: "Uniforme de Mikasa Ackerman (Shingeki no Kyojin)", en: "Mikasa Ackerman's uniform (Attack on Titan)" },
            { es: "Disfraz de Sailor Moon", en: "Sailor Moon costume" },
            { es: "Traje de Zero Two (Darling in the Franxx)", en: "Zero Two's pilot suit (Darling in the Franxx)" },
            { es: "Cosplay de Mai Sakurajima (conejita)", en: "Mai Sakurajima bunny girl cosplay" },
            { es: "Disfraz de Elfa Oscura sexy", en: "Sultry Dark Elf cosplay" },
            { es: "Cosplay de Morrigan Aensland (Darkstalkers)", en: "Morrigan Aensland cosplay (Darkstalkers)" },
            { es: "Atuendo de Cammy White (Street Fighter)", en: "Cammy White's leotard (Street Fighter)" },
            { es: "Ropa interior manchada de orina", en: "Urine-stained underwear" },
            { es: "Vestido de látex para 'vac-bed'", en: "Vac-bed latex suit" },
            { es: "Traje de 'pony play' con bocado", en: "Pony play gear with a bit gag" },
            { es: "Solo un arnés de 'strapon'", en: "Wearing only a strapon harness" },
            { es: "Atuendo de esclava sexual alienígena", en: "Alien sex slave attire" },
        ],
    },
    {
        id: 'accessories',
        label: 'accessories',
        singleSelect: false,
        initialVisible: 8,
        optionsPool: [
            { es: "Gargantilla de Púas", en: "spiked choker" },
            { es: "Piercing en el Septo", en: "septum piercing" },
            { es: "Gafas", en: "glasses" },
            { es: "Cadenas Corporales de Oro", en: "gold body chains" },
            { es: "Mordaza de Bola", en: "ball gag" },
            { es: "Esposas", en: "handcuffs" },
            { es: "Anillos en Todos los Dedos", en: "rings on every finger" },
            { es: "Látigo de Montar", en: "riding crop" },
            { es: "Collar de Perro", en: "collar with a leash" },
            { es: "Guantes de Ópera de Satén", en: "satin opera gloves" },
            { es: "Máscara Veneciana", en: "venetian mask" },
            { es: "Venda en los Ojos", en: "silk blindfold" },
            { es: "Piercing de Nariz", en: "nose ring" },
            { es: "Auriculares Retro", en: "retro headphones" },
            { es: "Sombrero de Ala Ancha", en: "wide-brimmed hat" },
            { es: "Cadenas (Shibari)", en: "shibari rope harness" },
            { es: "Joyas Corporales", en: "body jewelry" },
            { es: "Boquilla de Cigarrillo Larga", en: "long cigarette holder" },
            { es: "Corbata Desatada", en: "loosened tie" },
            { es: "Arnés para Piernas", en: "leg harness" },
            { es: "Pistola de Atrezo", en: "prop gun" },
            { es: "Abanico de Plumas", en: "feather fan" },
            { es: "Vibrador de Varita Mágica", en: "magic wand vibrator" },
            { es: "Pezoneras de Cristal", en: "crystal pasties" },
            { es: "Cinturón de Castidad", en: "chastity belt" },
            { es: "Lentes de Contacto de Fantasía", en: "fantasy contact lenses" },
            { es: "Velas y Cera Derretida", en: "candles and melted wax" },
            { es: "Cuchillo de Atrezo", en: "prop knife" },
            { es: "Tapón Anal con Cola de Zorro", en: "fox tail butt plug" },
            { es: "Corona de Espinas", en: "crown of thorns" },
            { es: "Pintura Corporal", en: "body paint" },
            { es: "Máscara de Gas", en: "gas mask" },
            { es: "Rosario", en: "rosary beads" },
            { es: "Dildo de Cristal", en: "glass dildo" },
            { es: "Casco de Moto", en: "motorcycle helmet" },
            { es: "Cigarro Cubano", en: "cigar" },
            { es: "Cámara Polaroid", en: "Polaroid camera" },
            { es: "Copa de Vino", en: "glass of wine" },
            { es: "Espada de Atrezo", en: "prop sword" },
            { es: "Libro de Poesía", en: "book of poetry" },
            { es: "Fajo de billetes", en: "Wad of cash" },
            { es: "Manchas de fluidos corporales", en: "Body fluid stains" },
            { es: "Gancho anal", en: "Anal hook" },
            { es: "Sonda uretral", en: "Urethral sound" },
            { es: "Espéculo vaginal", en: "Vaginal speculum" },
            { es: "Jeringuillas (atrezo)", en: "Syringes (prop)" },
            { es: "Máscara de cerdo", en: "Pig nose mask" },
            { es: "Mordaza de anilla con babeo", en: "O-ring gag with drool" },
            { es: "Paleta de nalgadas", en: "Spanking paddle" },
            { es: "Pinzas para pezones", en: "Nipple clamps" },
            { es: "Vibrador Sybian", en: "Sybian machine" },
            { es: "Juguetes de electroestimulación", en: "E-stim toys" },
            { es: "Correa y bozal de cachorro", en: "Puppy leash and muzzle" },
            { es: "Pendientes de aro grandes", en: "Large hoop earrings" },
            { es: "Múltiples pendientes en las orejas", en: "Multiple ear piercings" },
            { es: "Piercing en el ombligo", en: "Belly button piercing" },
            { es: "Piercing en la ceja", en: "Eyebrow piercing" },
            { es: "Piercing en el labio", en: "Lip piercing" },
            { es: "Piercing en la lengua", en: "Tongue piercing" },
            { es: "Piercing genital", en: "Genital piercing" },
            { es: "Gancho para la nariz", en: "Nose hook" },
            { es: "Mordaza de araña", en: "Spider gag" },
            { es: "Dilatador anal", en: "Butt plug spreader" },
            { es: "Máquina de ordeño (atrezo)", en: "Milking machine (prop)" },
            { es: "Electrodo de consolador", en: "E-stim dildo" },
            { es: "Jaula para la cabeza", en: "Head cage" },
        ],
    },
    {
        id: 'location',
        label: 'location',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Mazmorra BDSM", en: "BDSM dungeon" },
            { es: "Ático de Lujo", en: "Luxury penthouse" },
            { es: "Almacén Abandonado", en: "Abandoned warehouse" },
            { es: "Cuarto Oscuro de Discoteca", en: "Nightclub backroom" },
            { es: "Playa Pública", en: "Public beach" },
            { es: "Claro en el Bosque", en: "Forest clearing" },
            { es: "Nave Espacial", en: "Spaceship" },
            { es: "Catedral Gótica", en: "Gothic cathedral" },
            { es: "Callejón Lluvioso", en: "Rainy alleyway" },
            { es: "Habitación de Hotel", en: "Hotel room" },
            { es: "Piscina", en: "Swimming pool" },
            { es: "Biblioteca", en: "Library" },
            { es: "Sauna", en: "Sauna" },
            { es: "Jacuzzi", en: "Jacuzzi" },
            { es: "Azotea", en: "Rooftop" },
            { es: "Jet Privado", en: "Private jet" },
            { es: "Yate de Lujo", en: "Luxury yacht" },
            { es: "Casino", en: "Casino" },
            { es: "Baño Público", en: "Public restroom" },
            { es: "Coche Clásico", en: "Classic car" },
            { es: "Parque de Atracciones", en: "Amusement park" },
            { es: "Oficina por la Noche", en: "Office at night" },
            { es: "Cementerio", en: "Cemetery" },
            { es: "Bar de Neón", en: "Neon-lit bar" },
            { es: "Ruinas Antiguas", en: "Ancient ruins" },
            { es: "Sala de Interrogatorios", en: "Interrogation room" },
            { es: "Laboratorio de Científico Loco", en: "Mad scientist's laboratory" },
            { es: "Altar de Sacrificios", en: "Sacrificial altar" },
            { es: "Invernadero Exótico por la Noche", en: "Exotic greenhouse at night" },
            { es: "Dentro de un Coche en un Autocine", en: "Inside a car at a drive-in theater" },
            { es: "Sala de Espejos", en: "Hall of mirrors" },
            { es: "Plataforma Petrolífera", en: "Oil rig" },
            { es: "Confesionario de Iglesia", en: "Church confessional" },
            { es: "Ring de Boxeo", en: "Boxing ring" },
            { es: "Cabina de un Camión", en: "Truck cabin" },
            { es: "Morgue", en: "Morgue" },
            { es: "Fábrica Abandonada", en: "Derelict factory" },
            { es: "Tienda de Campaña Durante una Tormenta", en: "Tent during a thunderstorm" },
            { es: "Vagón de Tren de Lujo", en: "Luxury train car" },
            { es: "Cama de Agua Retro", en: "Retro waterbed" },
            { es: "Junto a un Lamborghini", en: "Next to a Lamborghini" },
            { es: "Mesa de poker", en: "Poker table" },
            { es: "Pista de tenis", en: "Tennis court" },
            { es: "Bolera de lujo", en: "Luxury bowling alley" },
            { es: "Probador de una tienda", en: "Department store fitting room" },
            { es: "Cine para adultos", en: "Adult movie theater" },
            { es: "Balcón de un hotel con vistas a la ciudad", en: "Hotel balcony overlooking the city" },
            { es: "Vagón de metro lleno de gente", en: "Crowded subway car" },
            { es: "Ascensor de cristal", en: "Glass elevator" },
            { es: "Psiquiátrico abandonado", en: "Abandoned asylum" },
            { es: "Escena de un crimen", en: "Crime scene" },
            { es: "Matadero", en: "Slaughterhouse" },
            { es: "Sótano de tortura", en: "Torture basement" },
            { es: "Sauna mixta", en: "Co-ed sauna" },
            { es: "Baño de un gloryhole", en: "Gloryhole bathroom stall" },
            { es: "Set de una película snuff", en: "Snuff film set" },
            { es: "Clínica de abortos abandonada", en: "Abandoned abortion clinic" },
            { es: "Hogar familiar incestuoso", en: "Incestuous family home" },
            { es: "Escenario de humillación pública", en: "Public humiliation stage" },
            { es: "Matadero humano", en: "Human slaughterhouse" },
            { es: "Nido de monstruos alienígenas", en: "Alien monster nest" },
            { es: "Piscina llena de fluidos", en: "Fluid-filled pool" },
            { es: "Circo de fenómenos abandonado", en: "Abandoned freak show" },
            { es: "Cámara de gas (escenario)", en: "Gas chamber (setting)" },
            { es: "Laboratorio de experimentación humana", en: "Human experimentation lab" },
            { es: "Dentro de un ataúd", en: "Inside a coffin" },
        ],
    },
    {
        id: 'action',
        label: 'action',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Mirando a la cámara", en: "looking seductively at the camera" },
            { es: "De espaldas", en: "shot from behind" },
            { es: "Arrodillada", en: "kneeling" },
            { es: "Tumbada en la cama", en: "lying on bed" },
            { es: "Bailando sensualmente", en: "sensually dancing" },
            { es: "Tocándose", en: "touching herself" },
            { es: "Sentada en una silla", en: "sitting on a chair" },
            { es: "Apoyada en la pared", en: "leaning against a wall" },
            { es: "Corriendo los dedos por el pelo", en: "running fingers through hair" },
            { es: "Metiéndose los dedos en la boca", en: "fingers in mouth" },
            { es: "Arqueando la espalda", en: "arching her back" },
            { es: "Abriendo las piernas", en: "spreading her legs" },
            { es: "Mordiendo el labio", en: "biting her lip" },
            { es: "A cuatro patas", en: "on all fours" },
            { es: "Con los brazos sobre la cabeza", en: "arms above head" },
            { es: "Lamiendo un objeto", en: "licking an object" },
            { es: "Derramando líquido sobre sí misma", en: "pouring liquid on herself" },
            { es: "Tirando de su pelo", en: "pulling her hair" },
            { es: "En cuclillas", en: "squatting" },
            { es: "Sentada en el suelo", en: "sitting on the floor" },
            { es: "Sosteniendo una cuerda", en: "holding a rope" },
            { es: "En el espejo", en: "in the mirror" },
            { es: "Atada", en: "tied up" },
            { es: "Fumando", en: "smoking" },
            { es: "Bebiendo de una copa", en: "drinking from a glass" },
            { es: "Sosteniendo un Cráneo", en: "holding a skull" },
            { es: "Bañándose en Leche", en: "bathing in milk" },
            { es: "Pintando su Cuerpo", en: "painting her body" },
            { es: "Jugando con Fuego", en: "playing with fire" },
            { es: "Destrozando una Habitación de Hotel", en: "trashing a hotel room" },
            { es: "Comiendo Fruta de Forma Sugerente", en: "suggestively eating fruit" },
            { es: "Acariciando una Serpiente", en: "caressing a snake" },
            { es: "Reparando un Coche", en: "fixing a car" },
            { es: "Levitando", en: "levitating" },
            { es: "Saliendo del Agua a Cámara Lenta", en: "emerging from water in slow motion" },
            { es: "Rompiendo Cadenas", en: "breaking chains" },
            { es: "Leyendo un Libro Prohibido", en: "reading a forbidden book" },
            { es: "Tocando el Violín", en: "playing a violin" },
            { es: "Realizando un Ritual", en: "performing a ritual" },
            { es: "Suspendida en el Aire", en: "suspended in mid-air" },
            { es: "Fumando y echando humo", en: "smoking and blowing smoke" },
            { es: "Conduciendo un hiperdeportivo", en: "Driving a hypercar" },
            { es: "Apostando en un casino", en: "Gambling at a casino" },
            { es: "Jugando al tenis", en: "Playing tennis" },
            { es: "Jugando a los bolos", en: "Playing bowling" },
            { es: "Exhibiéndose en público", en: "Flashing in public" },
            { es: "Teniendo un orgasmo visible", en: "Having a visible orgasm" },
            { es: "Siendo observada sin saberlo (voyeur)", en: "Being watched unknowingly (voyeur)" },
            { es: "Lamiendo un cuchillo", en: "Licking a knife" },
            { es: "Cubierta de sangre (falsa)", en: "Covered in (fake) blood" },
            { es: "Orinando en público", en: "Peeing in public" },
            { es: "Siendo sometida", en: "Being subjugated" },
            { es: "Jugando con fluidos corporales", en: "Playing with body fluids" },
            { es: "En un acto de auto-bondage (shibari)", en: "Performing self-bondage (shibari)" },
            { es: "Asfixia erótica (breath play)", en: "Erotic asphyxiation (breath play)" },
            { es: "Siendo violada por un grupo (CNC)", en: "Being gangbanged (CNC)" },
            { es: "Haciendo una garganta profunda a un dildo enorme", en: "Deepthroating a huge dildo" },
            { es: "Siendo sometida a fisting anal", en: "Being anally fisted" },
            { es: "Orinándose encima", en: "Pissing on herself" },
            { es: "Recibiendo un creampie", en: "Receiving a creampie" },
            { es: "Siendo usada como un cenicero humano", en: "Being used as a human ashtray" },
            { es: "Lamiendo un inodoro sucio", en: "Licking a dirty toilet" },
            { es: "Comiendo semen", en: "Eating cum" },
            { es: "Siendo inseminada a la fuerza", en: "Being forcibly inseminated" },
            { es: "Siendo usada como urinario", en: "Being used as a urinal" },
            { es: "Recibiendo una lluvia dorada", en: "Receiving a golden shower" },
            { es: "Sufriendo 'ballbusting'", en: "Enduring ballbusting" },
            { es: "Siendo marcada con un hierro (atrezo)", en: "Being branded (prop)" },
            { es: "Participando en 'sounding' uretral", en: "Undergoing urethral sounding" },
            { es: "Siendo forzada a lamer botas", en: "Being forced to lick boots" },
            { es: "Recibiendo una doble penetración anal", en: "Receiving double anal penetration" },
            { es: "Sufriendo un prolapso rectal (ficticio)", en: "Undergoing a rectal prolapse (fictional)" },
            { es: "Comiendo vómito (ficticio)", en: "Eating vomit (fictional)" },
            { es: "Siendo usada en un 'spitroast'", en: "Being spitroasted" },
        ],
    },
    {
        id: 'lighting',
        label: 'lighting',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Luz de Neón", en: "neon lighting" },
            { es: "Luz de Velas", en: "candlelight" },
            { es: "Luz Solar Directa", en: "direct sunlight" },
            { es: "Hora Dorada", en: "golden hour lighting" },
            { es: "Luz de Estudio", en: "studio lighting" },
            { es: "Cinematográfica", en: "cinematic lighting" },
            { es: "Tenue y Sensual", en: "dim, moody lighting" },
            { es: "Contraluz", en: "backlit" },
            { es: "Sombras Marcadas", en: "dramatic hard shadows" },
            { es: "Luz de Luna", en: "moonlight" },
            { es: "Filtro de Color Rojo", en: "red color gel filter" },
            { es: "Reflejos de Lente", en: "lens flare" },
            { es: "Luz Estroboscópica", en: "strobe lighting" },
            { es: "Luz Natural de Ventana", en: "natural window light" },
            { es: "Iluminación Subacuática", en: "underwater lighting" },
            { es: "Fuego/Hoguera", en: "firelight" },
            { es: "Luz de Proyector", en: "projector light" },
            { es: "Silueta", en: "silhouette" },
            { es: "Luz Volumétrica", en: "volumetric lighting" },
            { es: "Filtro de Color Azul", en: "blue color gel filter" },
            { es: "Luz Negra (UV)", en: "blacklight (UV)" },
            { es: "Proyección de Patrones (Gobos)", en: "gobo light patterns" },
            { es: "Luz de Bengalas", en: "flare lighting" },
            { es: "Focos de Helicóptero", en: "helicopter searchlight" },
            { es: "Iluminación de Sala de Operaciones", en: "operating room lighting" },
            { es: "Luz Filtrada a Través de Persianas", en: "light filtering through blinds" },
            { es: "Reflejos de una Bola de Discoteca", en: "disco ball reflections" },
            { es: "Luz Parpadeante de un Televisor", en: "flickering television light" },
            { es: "Amanecer Brumoso", en: "misty sunrise light" },
            { es: "Luz de Faro", en: "lighthouse beam" },
            { es: "Luz de uma Pantalla de Ordenador", en: "computer screen glow" },
            { es: "Fuego de Chimenea", en: "fireplace light" },
            { es: "Iluminación de Acuario", en: "aquarium lighting" },
            { es: "Rayos y Relámpagos", en: "lightning flashes" },
            { es: "Brillo Etéreo", en: "ethereal glow" },
            { es: "Luz dura de interrogatorio", en: "Harsh interrogation light" },
            { es: "Luces parpadeantes de morgue", en: "Flickering morgue lights" },
            { es: "Resplandor de barrio rojo", en: "Red light district glow" },
            { es: "Luz estroboscópica revelando fluidos", en: "Strobe light revealing fluids" },
            { es: "Luz verde de visión nocturna", en: "Night vision green glow" },
        ],
    },
    {
        id: 'cameraAngle',
        label: 'cameraAngle',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Punto de Vista (POV)", en: "Point-of-view (POV)" },
            { es: "Plano Contrapicado", en: "Low-angle shot" },
            { es: "Plano General Amplio", en: "Wide shot" },
            { es: "Primerísimo Plano", en: "Extreme close-up" },
            { es: "Cámara en Mano/Inestable", en: "Handheld/shaky cam" },
            { es: "Plano Cenital", en: "Overhead shot" },
            { es: "Plano Holandés", en: "Dutch angle" },
            { es: "Desde Atrás", en: "Shot from behind" },
            { es: "Selfie", en: "Selfie" },
            { es: "Plano Medio", en: "Medium shot" },
            { es: "Por encima del hombro", en: "Over the shoulder shot" },
            { es: "A través de un ojo de cerradura", en: "Through a keyhole" },
            { es: "Plano Detalle", en: "Detail shot" },
            { es: "Cámara a nivel del suelo", en: "Ground-level shot" },
            { es: "Plano Americano", en: "American shot" },
            { es: "Reflejo", en: "Reflection shot" },
            { es: "Ojo de Pez", en: "Fisheye lens" },
            { es: "Fotografía Macro", en: "Macro photography" },
            { es: "Plano Aéreo", en: "Aerial shot" },
            { es: "Cámara Lenta", en: "Slow motion" },
            { es: "Plano Nadir (desde abajo)", en: "Nadir shot (from directly below)" },
            { es: "Cámara Subjetiva", en: "Subjective camera" },
            { es: "Plano Secuencia", en: "Sequence shot" },
            { es: "Bullet Time (efecto Matrix)", en: "Bullet time effect" },
            { es: "Vista de Dron", en: "Drone view" },
            { es: "Cámara de Seguridad", en: "Security camera footage" },
            { es: "A través de un Vaso o Botella", en: "Shot through a glass or bottle" },
            { es: "Fotografía con Teleobjetivo", en: "Telephoto lens shot" },
            { es: "Gran Angular Extremo (distorsión)", en: "Extreme wide-angle (distortion)" },
            { es: "Plano Inserto", en: "Insert shot" },
            { es: "Zoom Rápido", en: "Whip zoom" },
            { es: "Cámara Montada en el Cuerpo", en: "Body-mounted camera" },
            { es: "Plano sobre el Agua", en: "Over-under water shot" },
            { es: "Desde Dentro de una Boca", en: "Shot from inside a mouth" },
            { es: "Fotografía Cenital con el Sujeto Tumbado", en: "Top-down shot of subject lying down" },
            { es: "GoPro montada en un dildo", en: "GoPro mounted on a dildo" },
            { es: "Vista desde dentro de un gloryhole", en: "View from inside a gloryhole" },
            { es: "Grabación de cámara espía oculta", en: "Hidden spy cam footage" },
            { es: "Plano bajo la falda", en: "Upskirt shot" },
            { es: "Cámara endoscópica", en: "Endoscopic camera view" },
        ],
    },
    {
        id: 'style',
        label: 'style',
        singleSelect: true,
        initialVisible: 6,
        excludeFromRandom: true,
        optionsPool: [
             { es: "Fotorrealista", en: "photorealistic" },
             { es: "Hiperrealista", en: "hyperrealistic, 8k" },
             { es: "Cinematográfico", en: "cinematic, film grain" },
             { es: "Fantasía Oscura", en: "dark fantasy" },
             { es: "Ciberpunk", en: "cyberpunk, neon lighting" },
             { es: "Vaporwave", en: "vaporwave aesthetic" },
             { es: "Steampunk", en: "steampunk" },
             { es: "Blanco y Negro", en: "black and white photo" },
             { es: "Polaroid", en: "polaroid photo" },
             { es: "Vintage", en: "vintage photo" },
             { es: "Gótico", en: "gothic" },
             { es: "Arte Digital", en: "digital art" },
             { es: "Estilo Anime", en: "anime style" },
             { es: "Pintura al Óleo", en: "oil painting" },
             { es: "Arte Conceptual", en: "concept art" },
             { es: "Surrealista", en: "surreal" },
             { es: "Impresionista", en: "impressionistic" },
             { es: "Glitch Art", en: "glitch art" },
             { es: "Estilo Cómic", en: "comic book style" },
             { es: "Doble Exposición", en: "double exposure" },
             { es: "Estilo de H.R. Giger", en: "in the style of H.R. Giger, biomechanical" },
             { es: "Estilo de Caravaggio (claroscuro)", en: "in the style of Caravaggio, chiaroscuro" },
             { es: "Estilo de Manara (cómic erótico)", en: "in the style of Milo Manara, erotic comic art" },
             { es: "Estilo de Hajime Sorayama (aerografía)", en: "in the style of Hajime Sorayama, airbrush art" },
             { es: "Estilo de Luis Royo (fantasía)", en: "in the style of Luis Royo, fantasy art" },
             { es: "Renderizado de Octane", en: "Octane render" },
             { es: "Estilo de los 90 (grunge)", en: "90s grunge aesthetic" },
             { es: "Película de Terror Encontrada", en: "found footage horror film style" },
             { es: "Estilo de Videoclip de los 80", en: "80s music video style" },
             { es: "Barroco", en: "Baroque" },
             { es: "Art Nouveau", en: "Art Nouveau" },
             { es: "Pintura Prerrafaelita", en: "Pre-Raphaelite painting" },
             { es: "Fotografía de Moda de Alta Costura", en: "haute couture fashion photography" },
             { es: "Infografía Térmica", en: "thermal imaging" },
             { es: "Daguerrotipo", en: "daguerreotype" },
             { es: "Estilo de fotografía forense", en: "Forensic photography style" },
             { es: "Capturado en una webcam barata", en: "Captured on a cheap webcam" },
             { es: "Grabación de bodycam", en: "Bodycam footage" },
             { es: "Estilo de película de terror japonesa (J-horror)", en: "J-horror film style" },
             { es: "Estilo de David Lynch", en: "Lynchian, surreal horror" },
        ]
    },
    SPECIFIC_FETISHES_CATEGORY_CONFIG,
    EXTRA_PEOPLE_CATEGORY_CONFIG
];

export const PROMPT_CATEGORIES_CONFIG: PromptCategoryConfig[] = [
    {
        id: 'ethnicity',
        label: 'ethnicity',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Latina", en: "Latina" },
            { es: "Asiática", en: "Asian" },
            { es: "Negra", en: "Black" },
            { es: "Caucásica", en: "Caucasian" },
            { es: "India", en: "Indian" },
            { es: "Oriente Medio", en: "Middle Eastern" },
            { es: "Mestiza", en: "Mixed Race" },
            { es: "Nativa Americana", en: "Native American" },
            { es: "Isleña del Pacífico", en: "Pacific Islander" },
            { es: "Escandinava", en: "Scandinavian" },
            { es: "Mediterránea", en: "Mediterranean" },
            { es: "Eslava", en: "Slavic" },
            { es: "Afro-Latina", en: "Afro-Latina" },
            { es: "Blasian (Negra/Asiática)", en: "Blasian" },
            { es: "Hapa (Asiática/Blanca)", en: "Hapa" },
            { es: "Árabe", en: "Arab" },
            { es: "Persa", en: "Persian" },
            { es: "Filipina", en: "Filipina" },
            { es: "Polinesia", en: "Polynesian" },
            { es: "Hispana", en: "Hispanic" },
            { es: "Gitana", en: "Romani" },
            { es: "Celta", en: "Celtic" },
            { es: "Nórdica", en: "Norse" },
            { es: "Amazona Mítica", en: "Mythical Amazonian" },
            { es: "Valquiria", en: "Valkyrie" },
            { es: "Elfa Oscura", en: "Dark Elf" },
            { es: "Súcubo", en: "Succubus" },
            { es: "Ciborg", en: "Cyborg" },
            { es: "Vampiresa", en: "Vampire" },
            { es: "Androide", en: "Android" },
            { es: "Demonio", en: "Demonic" },
            { es: "Criatura Feérica", en: "Fae" },
            { es: "Genio (Djinn)", en: "Djinn" },
            { es: "Siberiana", en: "Siberian" },
            { es: "Bereber", en: "Berber" },
            { es: "Mujer-Gato (Neko)", en: "Catgirl (Neko)" },
            { es: "Orco", en: "Orc" },
            { es: "Goblin", en: "Goblin" },
            { es: "Reptiliana", en: "Reptilian" },
        ],
    },
    {
        id: 'hairColor',
        label: 'hairColor',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Rubia", en: "Blonde hair" },
            { es: "Morena", en: "Brunette hair" },
            { es: "Negro", en: "Black hair" },
            { es: "Pelirroja", en: "Redhead" },
            { es: "Rosa", en: "Pink hair" },
            { es: "Azul", en: "Blue hair" },
            { es: "Verde", en: "Green hair" },
            { es: "Platino", en: "Platinum blonde hair" },
            { es: "Gris", en: "Grey hair" },
            { es: "Morado", en: "Purple hair" },
            { es: "Naranja", en: "Orange hair" },
            { es: "Arcoíris", en: "Rainbow hair" },
            { es: "Plata", en: "Silver hair" },
            { es: "Ombre", en: "Ombre hair" },
            { es: "Balayage", en: "Balayage hair" },
            { es: "Pastel", en: "Pastel hair" },
            { es: "Castaño Claro", en: "Light brown hair" },
            { es: "Rojo Intenso", en: "Vibrant red hair" },
            { es: "Turquesa", en: "Turquoise hair" },
            { es: "Blanco", en: "White hair" },
            { es: "Castaño Ceniza", en: "Ash brown hair" },
            { es: "Rubio Fresa", en: "Strawberry blonde hair" },
            { es: "Cobre", en: "Copper hair" },
            { es: "Borgoña", en: "Burgundy hair" },
            { es: "Azul Medianoche", en: "Midnight blue hair" },
            { es: "Verde Esmeralda", en: "Emerald green hair" },
            { es: "Lavanda", en: "Lavender hair" },
            { es: "Coral", en: "Coral hair" },
            { es: "Neón", en: "Neon hair" },
            { es: "Bicolor (dividido)", en: "Split-dyed hair" },
            { es: "Con Mechas", en: "Highlighted hair" },
            { es: "Puntas Teñidas", en: "Dip-dyed hair" },
            { es: "Tinte Metálico", en: "Metallic hair" },
            { es: "Brilla en la Oscuridad", en: "Glow-in-the-dark hair" },
            { es: "Holográfico", en: "Holographic hair" },
            { es: "Pelo escarchado con semen", en: "Semen-frosted hair" },
        ],
    },
    {
        id: 'hairStyle',
        label: 'hairStyle',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Largo y Liso", en: "Long and straight hair" },
            { es: "Ondas de Playa", en: "Beach waves" },
            { es: "Rizado y Salvaje", en: "Curly and wild hair" },
            { es: "Pelo con Mucho Volumen", en: "Voluminous blowout hair" },
            { es: "Ondas de Hollywood Glamurosas", en: "Glamorous Hollywood waves" },
            { es: "Cola de Caballo Alta", en: "High ponytail" },
            { es: "Recogido con Mechones Sueltos", en: "Updo with loose, face-framing tendrils" },
            { es: "Moño Desordenado y Sexy", en: "Sexy messy bun" },
            { es: "Moño Alto Pulido", en: "Sleek high bun" },
            { es: "Recogido Elegante", en: "Elegant updo" },
            { es: "Coletas Juguetonas", en: "Playful pigtails" },
            { es: "Trenzas", en: "Braids" },
            { es: "Trenza de Cascada", en: "Waterfall braid" },
            { es: "Corte Bob", en: "Bob cut" },
            { es: "Media Melena Ondulada", en: "Wavy lob haircut" },
            { es: "Corte Pixie", en: "Pixie cut" },
            { es: "Cabeza Rapada", en: "Shaved head" },
            { es: "Rastas", en: "Dreadlocks" },
            { es: "Afro", en: "Afro hair" },
            { es: "Mohicano", en: "Mohawk" },
            { es: "Rapado a un lado", en: "Side-shave" },
            { es: "Trenzas de Boxeadora", en: "Boxer braids" },
            { es: "Flequillo", en: "Bangs" },
            { es: "Corte Mullet", en: "Mullet" },
            { es: "Pelo Mojado", en: "Wet hair look" },
            { es: "Corte asimétrico", en: "Asymmetrical cut" },
            { es: "Trenza de Cola de Pez", en: "Fishtail braid" },
            { es: "Moños Espaciales", en: "Space buns" },
            { es: "Recogido con Palillos", en: "Hair held up with chopsticks" },
            { es: "Victoriano Complejo", en: "Complex Victorian updo" },
            { es: "Corte 'Wolf Cut'", en: "Wolf cut" },
            { es: "Ondas al Agua", en: "Finger waves" },
            { es: "Corona de Trenzas", en: "Crown braid" },
            { es: "Permanente de los 80", en: "80s perm" },
            { es: "Pelo Engominado Hacia Atrás", en: "Slicked-back hair" },
            { es: "Cresta Punk", en: "Punk mohawk" },
            { es: "Corte 'Hime' Japonés", en: "Japanese hime cut" },
            { es: "Coletas de Burbuja", en: "Bubble pigtails" },
            { es: "Pelo con Adornos (flores, perlas)", en: "Hair adorned with (flowers, pearls)" },
            { es: "Rapado con Diseños", en: "Shaved head with patterns" },
            { es: "Extremadamente Largo (hasta el suelo)", en: "Extremely long, floor-length hair" },
            { es: "Pelo enmarañado con semen", en: "Semen-matted hair" },
            { es: "Pelo desordenado post-sexo", en: "Messy, post-coital hair" },
            { es: "Pelo agarrado con fuerza", en: "Hair being pulled forcefully" },
            { es: "Pelo empapado en sudor", en: "Sweat-drenched hair" },
            { es: "Pelo cubierto de glaseado", en: "Icing-covered hair" },
        ],
    },
    {
        id: 'bodyPart',
        label: 'bodyPart',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Tetas Enormes", en: "Huge tits" },
            { es: "Culo respingón", en: "Perky ass" },
            { es: "Cuerpo Delgado", en: "Slim body" },
            { es: "Muslos Gruesos", en: "Thick thighs" },
            { es: "Pezones Perforados", en: "Pierced nipples" },
            { es: "Tatuada", en: "Tattooed" },
            { es: "Pecas", en: "Freckles" },
            { es: "Abdominales Marcados", en: "Defined abs" },
            { es: "Caderas Anchas", en: "Wide hips" },
            { es: "Piel Pálida", en: "Pale skin" },
            { es: "Piel Bronceada", en: "Tanned skin" },
            { es: "Piercings", en: "Body piercings" },
            { es: "Piernas Largas", en: "Long legs" },
            { es: "Cintura Pequeña", en: "Small waist" },
            { es: "Piel Brillante", en: "Glistening skin" },
            { es: "Clavículas Definidas", en: "Defined clavicles" },
            { es: "Ojos Hipnóticos", en: "Hypnotic eyes" },
            { es: "Cuerpo Sudoroso", en: "Sweaty body" },
            { es: "Espalda Musculosa", en: "Muscular back" },
            { es: "Labios Carnosos", en: "Full lips" },
            { es: "Manos Delicadas", en: "Delicate hands" },
            { es: "Pies Bonitos", en: "Pretty feet" },
            { es: "Hombros Anchos", en: "Broad shoulders" },
            { es: "Hoyuelos", en: "Dimples" },
            { es: "Vientre Plano", en: "Flat stomach" },
            { es: "Lengua Bífida", en: "Forked tongue" },
            { es: "Cuerpo Cubierto de Aceite", en: "Oil-covered body" },
            { es: "Cicatrices", en: "Scars" },
            { es: "Orejas Puntiagudas (elfo)", en: "Pointy elf ears" },
            { es: "Colmillos (vampiro)", en: "Fangs" },
            { es: "Ojos Heterocromáticos", en: "Heterochromatic eyes" },
            { es: "Piel de Porcelana", en: "Porcelain skin" },
            { es: "Uñas Largas y Afiladas", en: "Long, sharp nails" },
            { es: "Espalda con Hoyuelos", en: "Dimples of Venus" },
            { es: "Implantes Subdérmicos", en: "Subdermal implants" },
            { es: "Costillas Visibles", en: "Visible ribs" },
            { es: "Modificaciones Corporales Extremas", en: "Extreme body modifications" },
            { es: "Cola Cibernética", en: "Cyborg tail" },
            { es: "Alas de Demonio", en: "Demon wings" },
            { es: "Articulaciones Mecánicas", en: "Mechanical joints" },
            { es: "Coño hinchado y usado", en: "Swollen, used pussy" },
            { es: "Labios vaginales visibles", en: "Visible labia lips" },
            { es: "Culo dilatado", en: "Gaped asshole" },
            { es: "Cuerpo cubierto de semen", en: "Semen-covered body" },
            { es: "Marcas de mordiscos y moratones", en: "Bite marks and bruises" },
            { es: "Coño afeitado", en: "Shaved pussy" },
            { es: "Pezones erectos y duros", en: "Hard, erect nipples" },
            { es: "Cameltoe pronunciado", en: "Prominent cameltoe" },
            { es: "Ano rosado y virgen", en: "Pink, virgin asshole" },
            { es: "Marcas de cuerdas (shibari)", en: "Rope marks (shibari)" },
            { es: "Clítoris perforado", en: "Pierced clit" },
            { es: "Leche goteando de los pechos", en: "Lactating, dripping breasts" },
            { es: "Estrías", en: "Stretch marks" },
            { es: "Ano prolapsado", en: "Anal prolapse" },
            { es: "Coño con creampie goteando", en: "Leaking creampie pussy" },
            { es: "Ano lleno de semen", en: "Semen-filled asshole" },
            { es: "Tetas cubiertas de semen", en: "Cum-covered tits" },
            { es: "Marcas de latigazos", en: "Whip marks" },
            { es: "Cuerpo atado con alambre de espino (atrezo)", en: "Body wrapped in (prop) barbed wire" },
        ],
    },
     {
        id: 'facialEmotion',
        label: 'facialEmotion',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Sonrisa Seductora", en: "seductive smile" },
            { es: "Mirada Intensa", en: "intense stare" },
            { es: "Labio Mordido", en: "biting lip" },
            { es: "Ojos Entornados de Placer", en: "eyes rolled back in pleasure" },
            { es: "Expresión de Éxtasis (Ahegao)", en: "ahegao face" },
            { es: "Mirada Inocente", en: "innocent look" },
            { es: "Sonrisa Burlona", en: "smirk" },
            { es: "Llorando", en: "crying" },
            { es: "Cara de Desdén", en: "scornful expression" },
            { es: "Mirada Soñadora", en: "dreamy look" },
            { es: "Expresión de Sorpresa", en: "surprised expression" },
            { es: "Boca Abierta", en: "mouth open" },
            { es: "Guiñando un Ojo", en: "winking" },
            { es: "Lengua Fuera", en: "tongue out" },
            { es: "Mirada de Dominación", en: "dominant gaze" },
            { es: "Expresión de Sumisión", en: "submissive expression" },
            { es: "Cejas Fruncidas (Enfado)", en: "angry eyebrows" },
            { es: "Riendo a Carcajadas", en: "laughing hysterically" },
            { es: "Mirada Vacía", en: "empty gaze" },
            { es: "Mejillas Sonrojadas", en: "blushing cheeks" },
            { es: "Mirada de Lujuria", en: "lustful gaze" },
            { es: "Sonrisa Tímida", en: "shy smile" },
            { es: "Lágrimas de Alegría", en: "tears of joy" },
            { es: "Mirada Desafiante", en: "defiant stare" },
            { es: "Expresión de Dolor Placentero", en: "pained pleasure expression" },
            { es: "Ceño de Concentración", en: "focused frown" },
            { es: "Mueca Juguetona", en: "playful pout" },
            { es: "Cara de Aburrimiento Altivo", en: "haughty, bored expression" },
            { es: "Ojos Vidriosos", en: "glassy eyes" },
            { es: "Mirada Suplicante", en: "pleading eyes" },
            { es: "Expresión Hambrienta", en: "hungry expression" },
            { es: "Risa Silenciosa", en: "silent laugh" },
            { es: "Cara Manchada de Lágrimas y Rímel", en: "tear-streaked, mascara-stained face" },
            { es: "Expresión Satisfecha", en: "smug, satisfied expression" },
            { es: "Mirada Feroz", en: "feral gaze" },
            { es: "Cara con la mente rota y babeando", en: "Mindbroken, drooling face" },
            { es: "Expresión humillada", en: "Humiliated expression" },
            { es: "Mirada de terror y excitación", en: "Look of terror and arousal" },
            { es: "Sonrisa forzada con lágrimas", en: "Forced smile with tears" },
            { es: "Ojos cruzados, en blanco", en: "Cross-eyed, blank expression" },
            { es: "Cara cubierta de saliva", en: "Spit-covered face" },
            { es: "Expresión de asfixia", en: "Choking expression" },
            { es: "Ojos suplicando piedad", en: "Eyes begging for mercy" },
            { es: "Sonrisa rota y psicótica", en: "Broken, psychotic smile" },
            { es: "Cara de humillación pública", en: "Publicly humiliated face" },
        ],
    },
    {
        id: 'outfit',
        label: 'outfit',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Traje de Látex", en: "Latex catsuit" },
            { es: "Medias de Red", en: "Fishnet stockings" },
            { es: "Lencería Gótica", en: "Gothic lingerie" },
            { es: "Uniforme Escolar", en: "Schoolgirl uniform" },
            { es: "Vestido Transparente", en: "Sheer dress" },
            { es: "Bragas sin Entrepierna", en: "Crotchless panties" },
            { es: "Arnés BDSM", en: "BDSM harness" },
            { es: "Nada", en: "Naked" },
            { es: "Disfraz de Criada", en: "Maid outfit" },
            { es: "Bikini", en: "Bikini" },
            { es: "Corsé", en: "Corset" },
            { es: "Botas Altas", en: "Thigh-high boots" },
            { es: "Body de Encaje", en: "Lace bodystocking" },
            { es: "Disfraz de Conejita", en: "Bunny suit" },
            { es: "Uniforme de Enfermera", en: "Nurse uniform" },
            { es: "Chaqueta de Cuero", en: "Leather jacket" },
            { es: "Solo Tacones", en: "Wearing nothing but heels" },
            { es: "Vestido de Noche", en: "Evening gown" },
            { es: "Ropa Deportiva", en: "Sportswear" },
            { es: "Kimono", en: "Kimono" },
            { es: "Disfraz de Animadora", en: "Cheerleader outfit" },
            { es: "Traje de Baño de una Pieza", en: "One-piece swimsuit" },
            { es: "Pijama de Seda", en: "Silk pajamas" },
            { es: "Minifalda", en: "Miniskirt" },
            { es: "Velo de Novia", en: "Bridal veil" },
            { es: "Armadura de Fantasía Reveladora", en: "Revealing fantasy armor" },
            { es: "Traje de Súcubo", en: "Succubus attire" },
            { es: "Uniforme de Azafata Retro", en: "Retro flight attendant uniform" },
            { es: "Disfraz de Supervillana", en: "Supervillain costume" },
            { es: "Vestido de Baile Hecho Jirones", en: "Tattered ball gown" },
            { es: "Atuendo Tribal", en: "Tribal wear" },
            { es: "Burka Transparente", en: "Sheer burqa" },
            { es: "Traje de Monja Profanado", en: "Desecrated nun's habit" },
            { es: "Ropa Bondage de Cuero y Hebillas", en: "Leather and buckles bondage wear" },
            { es: "Traje de Piloto de Carreras", en: "Race car driver suit" },
            { es: "Look Post-apocalíptico", en: "Post-apocalyptic gear" },
            { es: "Sari de Seda", en: "Silk sari" },
            { es: "Vestimenta de Sacerdotisa", en: "Priestess robes" },
            { es: "Traje de Sirena", en: "Mermaid costume" },
            { es: "Kimono Entreabierto", en: "Kimono falling open" },
            { es: "Uniforme Militar Fetichista", en: "Fetish military uniform" },
            { es: "Uniforme escolar roto y manchado", en: "Torn and stained schoolgirl uniform" },
            { es: "Traje de Gimp de cuero", en: "Leather gimp suit" },
            { es: "Bata de paciente de psiquiátrico", en: "Asylum patient gown" },
            { es: "Ropa interior usada y sucia", en: "Soiled, used underwear" },
            { es: "Delantal de 'cumslut'", en: "Cumslut apron" },
            { es: "Camisa de fuerza", en: "Straitjacket" },
            { es: "Solo un collar de perro", en: "Wearing only a dog collar" },
            // Cosplay - Superhéroes y Villanos
            { es: "Cosplay de Spider-Gwen", en: "Spider-Gwen cosplay" },
            { es: "Traje de Wonder Woman", en: "Wonder Woman costume" },
            { es: "Disfraz de Harley Quinn", en: "Harley Quinn costume" },
            { es: "Traje de Viuda Negra", en: "Black Widow suit" },
            { es: "Disfraz de Supergirl", en: "Supergirl outfit" },
            { es: "Traje de Catwoman", en: "Catwoman catsuit" },
            { es: "Atuendo de Bruja Escarlata", en: "Scarlet Witch attire" },
            { es: "Cosplay de Maléfica", en: "Maleficent cosplay" },
            { es: "Atuendo de Cruella de Vil", en: "Cruella de Vil outfit" },
            { es: "Disfraz de Bellatrix Lestrange", en: "Bellatrix Lestrange costume" },
            { es: "Cosplay de Mística (pintura corporal)", en: "Mystique cosplay (body paint)" },
            { es: "Traje de 'La Novia' (Kill Bill)", en: "The Bride's jumpsuit (Kill Bill)" },
            { es: "Disfraz de Reina Malvada", en: "Evil Queen costume" },
            { es: "Cosplay Femenino del Joker", en: "Female Joker cosplay" },
            // Cosplay - Anime y Videojuegos
            { es: "Cosplay de Asuka Langley (Evangelion)", en: "Asuka Langley cosplay (Evangelion)" },
            { es: "Traje de 2B (Nier: Automata)", en: "2B's outfit (Nier: Automata)" },
            { es: "Cosplay de Tifa Lockhart (Final Fantasy)", en: "Tifa Lockhart cosplay (Final Fantasy)" },
            { es: "Atuendo de Lucy (Cyberpunk: Edgerunners)", en: "Lucy's outfit (Cyberpunk: Edgerunners)" },
            { es: "Disfraz de Yor Forger (Spy x Family)", en: "Yor Forger's assassin dress (Spy x Family)" },
            { es: "Uniforme de Mikasa Ackerman (Shingeki no Kyojin)", en: "Mikasa Ackerman's uniform (Attack on Titan)" },
            { es: "Disfraz de Sailor Moon", en: "Sailor Moon costume" },
            { es: "Traje de Zero Two (Darling in the Franxx)", en: "Zero Two's pilot suit (Darling in the Franxx)" },
            { es: "Cosplay de Mai Sakurajima (conejita)", en: "Mai Sakurajima bunny girl cosplay" },
            { es: "Disfraz de Elfa Oscura sexy", en: "Sultry Dark Elf cosplay" },
            { es: "Cosplay de Morrigan Aensland (Darkstalkers)", en: "Morrigan Aensland cosplay (Darkstalkers)" },
            { es: "Atuendo de Cammy White (Street Fighter)", en: "Cammy White's leotard (Street Fighter)" },
            { es: "Ropa interior manchada de orina", en: "Urine-stained underwear" },
            { es: "Vestido de látex para 'vac-bed'", en: "Vac-bed latex suit" },
            { es: "Traje de 'pony play' con bocado", en: "Pony play gear with a bit gag" },
            { es: "Solo un arnés de 'strapon'", en: "Wearing only a strapon harness" },
            { es: "Atuendo de esclava sexual alienígena", en: "Alien sex slave attire" },
        ],
    },
    {
        id: 'accessories',
        label: 'accessories',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Gargantilla", en: "choker" },
            { es: "Gafas", en: "glasses" },
            { es: "Mordaza de Bola", en: "ball gag" },
            { es: "Esposas", en: "handcuffs" },
            { es: "Látigo", en: "whip" },
            { es: "Collar de Perro", en: "collar" },
            { es: "Guantes Largos", en: "long gloves" },
            { es: "Máscara", en: "mask" },
            { es: "Venda en los Ojos", en: "blindfold" },
            { es: "Piercing de Nariz", en: "nose ring" },
            { es: "Auriculares", en: "headphones" },
            { es: "Sombrero", en: "hat" },
            { es: "Cadenas", en: "chains" },
            { es: "Joyas Corporales", en: "body jewelry" },
            { es: "Cigarrillo", en: "cigarette" },
            { es: "Corbata", en: "tie" },
            { es: "Arnés para Piernas", en: "leg harness" },
            { es: "Pistola de Juguete", en: "toy gun" },
            { es: "Abanico", en: "fan" },
            { es: "Vibrador", en: "vibrator" },
            { es: "Piercings de Pezón con Cadena", en: "nipple piercings with chain" },
            { es: "Cinturón de Castidad", en: "chastity belt" },
            { es: "Lentes de Contacto de Fantasía", en: "fantasy contact lenses" },
            { es: "Velas y Cera Derretida", en: "candles and melted wax" },
            { es: "Cuchillo de Utilería", en: "prop knife" },
            { es: "Cuerdas (Shibari)", en: "shibari ropes" },
            { es: "Tapón Anal con Cola", en: "butt plug with a tail" },
            { es: "Corona de Espinas", en: "crown of thorns" },
            { es: "Pintura Corporal", en: "body paint" },
            { es: "Máscara de Gas", en: "gas mask" },
            { es: "Rosario", en: "rosary beads" },
            { es: "Espéculo Médico", en: "medical speculum" },
            { es: "Dildo de Cristal", en: "glass dildo" },
            { es: "Casco de Moto", en: "motorcycle helmet" },
            { es: "Cigarro Cubano", en: "cigar" },
            { es: "Fajo de billetes", en: "Wad of cash" },
            { es: "Manchas de fluidos corporales", en: "Body fluid stains" },
            { es: "Gancho anal", en: "Anal hook" },
            { es: "Sonda uretral", en: "Urethral sound" },
            { es: "Jeringuillas (atrezo)", en: "Syringes (prop)" },
            { es: "Máscara de cerdo", en: "Pig nose mask" },
            { es: "Mordaza de anilla con babeo", en: "O-ring gag with drool" },
            { es: "Paleta de nalgadas", en: "Spanking paddle" },
            { es: "Pinzas para pezones", en: "Nipple clamps" },
            { es: "Vibrador Sybian", en: "Sybian machine" },
            { es: "Juguetes de electroestimulación", en: "E-stim toys" },
            { es: "Correa y bozal de cachorro", en: "Puppy leash and muzzle" },
            { es: "Pendientes de aro grandes", en: "Large hoop earrings" },
            { es: "Múltiples pendientes en las orejas", en: "Multiple ear piercings" },
            { es: "Piercing en el ombligo", en: "Belly button piercing" },
            { es: "Piercing en la ceja", en: "Eyebrow piercing" },
            { es: "Piercing en el labio", en: "Lip piercing" },
            { es: "Piercing en la lengua", en: "Tongue piercing" },
            { es: "Piercing genital", en: "Genital piercing" },
            { es: "Gancho para la nariz", en: "Nose hook" },
            { es: "Mordaza de araña", en: "Spider gag" },
            { es: "Dilatador anal", en: "Butt plug spreader" },
            { es: "Máquina de ordeño (atrezo)", en: "Milking machine (prop)" },
            { es: "Electrodo de consolador", en: "E-stim dildo" },
            { es: "Jaula para la cabeza", en: "Head cage" },
        ]
    },
    {
        id: 'location',
        label: 'location',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Mazmorra BDSM", en: "BDSM dungeon" },
            { es: "Ático de Lujo", en: "Luxury penthouse" },
            { es: "Almacén Abandonado", en: "Abandoned warehouse" },
            { es: "Cuarto Oscuro de Discoteca", en: "Nightclub backroom" },
            { es: "Playa Pública", en: "Public beach" },
            { es: "Claro en el Bosque", en: "Forest clearing" },
            { es: "Nave Espacial", en: "Spaceship" },
            { es: "Catedral Gótica", en: "Gothic cathedral" },
            { es: "Callejón Lluvioso", en: "Rainy alleyway" },
            { es: "Habitación de Hotel", en: "Hotel room" },
            { es: "Piscina", en: "Swimming pool" },
            { es: "Biblioteca", en: "Library" },
            { es: "Sauna", en: "Sauna" },
            { es: "Jacuzzi", en: "Jacuzzi" },
            { es: "Azotea", en: "Rooftop" },
            { es: "Jet Privado", en: "Private jet" },
            { es: "Yate de Lujo", en: "Luxury yacht" },
            { es: "Casino", en: "Casino" },
            { es: "Baño Público", en: "Public restroom" },
            { es: "Coche Clásico", en: "Classic car" },
            { es: "Parque de Atracciones", en: "Amusement park" },
            { es: "Oficina por la Noche", en: "Office at night" },
            { es: "Cementerio", en: "Cemetery" },
            { es: "Bar de Neón", en: "Neon-lit bar" },
            { es: "Ruinas Antiguas", en: "Ancient ruins" },
            { es: "Sala de Interrogatorios", en: "Interrogation room" },
            { es: "Laboratorio de Científico Loco", en: "Mad scientist's laboratory" },
            { es: "Altar de Sacrificios", en: "Sacrificial altar" },
            { es: "Invernadero Exótico por la Noche", en: "Exotic greenhouse at night" },
            { es: "Dentro de un Coche en un Autocine", en: "Inside a car at a drive-in theater" },
            { es: "Sala de Espejos", en: "Hall of mirrors" },
            { es: "Plataforma Petrolífera", en: "Oil rig" },
            { es: "Confesionario de Iglesia", en: "Church confessional" },
            { es: "Ring de Boxeo", en: "Boxing ring" },
            { es: "Cabina de um Camión", en: "Truck cabin" },
            { es: "Morgue", en: "Morgue" },
            { es: "Fábrica Abandonada", en: "Derelict factory" },
            { es: "Tienda de Campaña Durante una Tormenta", en: "Tent during a thunderstorm" },
            { es: "Vagón de Tren de Lujo", en: "Luxury train car" },
            { es: "Cama de Agua Retro", en: "Retro waterbed" },
            { es: "Junto a un Lamborghini", en: "Next to a Lamborghini" },
            { es: "Mesa de poker", en: "Poker table" },
            { es: "Pista de tenis", en: "Tennis court" },
            { es: "Bolera de lujo", en: "Luxury bowling alley" },
            { es: "Probador de una tienda", en: "Department store fitting room" },
            { es: "Cine para adultos", en: "Adult movie theater" },
            { es: "Balcón de un hotel con vistas a la ciudad", en: "Hotel balcony overlooking the city" },
            { es: "Vagón de metro lleno de gente", en: "Crowded subway car" },
            { es: "Ascensor de cristal", en: "Glass elevator" },
            { es: "Psiquiátrico abandonado", en: "Abandoned asylum" },
            { es: "Escena de un crimen", en: "Crime scene" },
            { es: "Matadero", en: "Slaughterhouse" },
            { es: "Sótano de tortura", en: "Torture basement" },
            { es: "Sauna mixta", en: "Co-ed sauna" },
            { es: "Baño de un gloryhole", en: "Gloryhole bathroom stall" },
            { es: "Set de una película snuff", en: "Snuff film set" },
            { es: "Clínica de abortos abandonada", en: "Abandoned abortion clinic" },
            { es: "Hogar familiar incestuoso", en: "Incestuous family home" },
            { es: "Escenario de humillación pública", en: "Public humiliation stage" },
            { es: "Matadero humano", en: "Human slaughterhouse" },
            { es: "Nido de monstruos alienígenas", en: "Alien monster nest" },
            { es: "Piscina llena de fluidos", en: "Fluid-filled pool" },
            { es: "Circo de fenómenos abandonado", en: "Abandoned freak show" },
            { es: "Cámara de gas (escenario)", en: "Gas chamber (setting)" },
            { es: "Laboratorio de experimentación humana", en: "Human experimentation lab" },
            { es: "Dentro de un ataúd", en: "Inside a coffin" },
        ],
    },
    {
        id: 'action',
        label: 'action',
        singleSelect: false,
        initialVisible: 6,
        optionsPool: [
            { es: "Mirando a la cámara", en: "looking seductively at the camera" },
            { es: "De espaldas", en: "shot from behind" },
            { es: "Arrodillada", en: "kneeling" },
            { es: "Tumbada en la cama", en: "lying on bed" },
            { es: "Bailando sensualmente", en: "sensually dancing" },
            { es: "Tocándose", en: "touching herself" },
            { es: "Sentada en una silla", en: "sitting on a chair" },
            { es: "Apoyada en la pared", en: "leaning against a wall" },
            { es: "Corriendo los dedos por el pelo", en: "running fingers through hair" },
            { es: "Metiéndose los dedos en la boca", en: "fingers in mouth" },
            { es: "Arqueando la espalda", en: "arching her back" },
            { es: "Abriendo las piernas", en: "spreading her legs" },
            { es: "Mordiendo el labio", en: "biting her lip" },
            { es: "A cuatro patas", en: "on all fours" },
            { es: "Con los brazos sobre la cabeza", en: "arms above head" },
            { es: "Lamiendo un objeto", en: "licking an object" },
            { es: "Derramando líquido sobre sí misma", en: "pouring liquid on herself" },
            { es: "Tirando de su pelo", en: "pulling her hair" },
            { es: "En cuclillas", en: "squatting" },
            { es: "Sentada en el suelo", en: "sitting on the floor" },
            { es: "Sosteniendo una cuerda", en: "holding a rope" },
            { es: "En el espejo", en: "in the mirror" },
            { es: "Atada", en: "tied up" },
            { es: "Fumando", en: "smoking" },
            { es: "Bebiendo de una copa", en: "drinking from a glass" },
            { es: "Sosteniendo un Cráneo", en: "holding a skull" },
            { es: "Bañándose en Leche", en: "bathing in milk" },
            { es: "Pintando su Cuerpo", en: "painting her body" },
            { es: "Jugando con Fuego", en: "playing with fire" },
            { es: "Destrozando uma Habitación de Hotel", en: "trashing a hotel room" },
            { es: "Comiendo Fruta de Forma Sugerente", en: "suggestively eating fruit" },
            { es: "Acariciando una Serpiente", en: "caressing a snake" },
            { es: "Reparando un Coche", en: "fixing a car" },
            { es: "Levitando", en: "levitating" },
            { es: "Saliendo del Agua a Cámara Lenta", en: "emerging from water in slow motion" },
            { es: "Rompiendo Cadenas", en: "breaking chains" },
            { es: "Leyendo un Libro Prohibido", en: "reading a forbidden book" },
            { es: "Tocando el Violín", en: "playing a violin" },
            { es: "Realizando un Ritual", en: "performing a ritual" },
            { es: "Suspendida en el Aire", en: "suspended in mid-air" },
            { es: "Fumando y echando humo", en: "smoking and blowing smoke" },
            { es: "Conduciendo un hiperdeportivo", en: "Driving a hypercar" },
            { es: "Apostando en un casino", en: "Gambling at a casino" },
            { es: "Jugando al tenis", en: "Playing tennis" },
            { es: "Jugando a los bolos", en: "Playing bowling" },
            { es: "Exhibiéndose en público", en: "Flashing in public" },
            { es: "Teniendo un orgasmo visible", en: "Having a visible orgasm" },
            { es: "Siendo observada sin saberlo (voyeur)", en: "Being watched unknowingly (voyeur)" },
            { es: "Lamiendo un cuchillo", en: "Licking a knife" },
            { es: "Cubierta de sangre (falsa)", en: "Covered in (fake) blood" },
            { es: "Orinando en público", en: "Peeing in public" },
            { es: "Siendo sometida", en: "Being subjugated" },
            { es: "Jugando con fluidos corporales", en: "Playing with body fluids" },
            { es: "En un acto de auto-bondage (shibari)", en: "Performing self-bondage (shibari)" },
            { es: "Asfixia erótica (breath play)", en: "Erotic asphyxiation (breath play)" },
            { es: "Siendo violada por un grupo (CNC)", en: "Being gangbanged (CNC)" },
            { es: "Haciendo una garganta profunda a un dildo enorme", en: "Deepthroating a huge dildo" },
            { es: "Siendo sometida a fisting anal", en: "Being anally fisted" },
            { es: "Orinándose encima", en: "Pissing on herself" },
            { es: "Recibiendo un creampie", en: "Receiving a creampie" },
            { es: "Siendo usada como un cenicero humano", en: "Being used as a human ashtray" },
            { es: "Lamiendo un inodoro sucio", en: "Licking a dirty toilet" },
            { es: "Comiendo semen", en: "Eating cum" },
            { es: "Siendo inseminada a la fuerza", en: "Being forcibly inseminated" },
            { es: "Siendo usada como urinario", en: "Being used as a urinal" },
            { es: "Recibiendo una lluvia dorada", en: "Receiving a golden shower" },
            { es: "Sufriendo 'ballbusting'", en: "Enduring ballbusting" },
            { es: "Siendo marcada con un hierro (atrezo)", en: "Being branded (prop)" },
            { es: "Participando en 'sounding' uretral", en: "Undergoing urethral sounding" },
            { es: "Siendo forzada a lamer botas", en: "Being forced to lick boots" },
            { es: "Recibiendo una doble penetración anal", en: "Receiving double anal penetration" },
            { es: "Sufriendo un prolapso rectal (ficticio)", en: "Undergoing a rectal prolapse (fictional)" },
            { es: "Comiendo vómito (ficticio)", en: "Eating vomit (fictional)" },
            { es: "Siendo usada en un 'spitroast'", en: "Being spitroasted" },
            { es: "Formando un ciempiés humano", en: "Forming a human centipede" },
            { es: "Participando en una orgía de fluidos", en: "Participating in a fluid orgy" },
            { es: "Usándose mutuamente como muebles", en: "Using each other as human furniture" },
            { es: "Compitiendo por semen", en: "Competing for cum" },
            { es: "Compartiendo un consolador masivo", en: "Sharing a massive dildo" },
        ],
    },
    {
        id: 'lighting',
        label: 'lighting',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Luz de Neón", en: "neon lighting" },
            { es: "Luz de Velas", en: "candlelight" },
            { es: "Luz Solar Directa", en: "direct sunlight" },
            { es: "Hora Dorada", en: "golden hour lighting" },
            { es: "Luz de Estudio", en: "studio lighting" },
            { es: "Cinematográfica", en: "cinematic lighting" },
            { es: "Tenue y Sensual", en: "dim, moody lighting" },
            { es: "Contraluz", en: "backlit" },
            { es: "Sombras Marcadas", en: "dramatic hard shadows" },
            { es: "Luz de Luna", en: "moonlight" },
            { es: "Filtro de Color Rojo", en: "red color gel filter" },
            { es: "Reflejos de Lente", en: "lens flare" },
            { es: "Luz Estroboscópica", en: "strobe lighting" },
            { es: "Luz Natural de Ventana", en: "natural window light" },
            { es: "Iluminación Subacuática", en: "underwater lighting" },
            { es: "Fuego/Hoguera", en: "firelight" },
            { es: "Luz de Proyector", en: "projector light" },
            { es: "Silueta", en: "silhouette" },
            { es: "Luz Volumétrica", en: "volumetric lighting" },
            { es: "Filtro de Color Azul", en: "blue color gel filter" },
            { es: "Luz Negra (UV)", en: "blacklight (UV)" },
            { es: "Proyección de Patrones (Gobos)", en: "gobo light patterns" },
            { es: "Luz de Bengalas", en: "flare lighting" },
            { es: "Focos de Helicóptero", en: "helicopter searchlight" },
            { es: "Iluminación de Sala de Operaciones", en: "operating room lighting" },
            { es: "Luz Filtrada a Través de Persianas", en: "light filtering through blinds" },
            { es: "Reflejos de una Bola de Discoteca", en: "disco ball reflections" },
            { es: "Luz Parpadeante de un Televisor", en: "flickering television light" },
            { es: "Amanecer Brumoso", en: "misty sunrise light" },
            { es: "Luz de Faro", en: "lighthouse beam" },
            { es: "Luz de uma Pantalla de Ordenador", en: "computer screen glow" },
            { es: "Fuego de Chimenea", en: "fireplace light" },
            { es: "Iluminación de Acuario", en: "aquarium lighting" },
            { es: "Rayos y Relámpagos", en: "lightning flashes" },
            { es: "Brillo Etéreo", en: "ethereal glow" },
            { es: "Luz dura de interrogatorio", en: "Harsh interrogation light" },
            { es: "Luces parpadeantes de morgue", en: "Flickering morgue lights" },
            { es: "Resplandor de barrio rojo", en: "Red light district glow" },
            { es: "Luz estroboscópica revelando fluidos", en: "Strobe light revealing fluids" },
            { es: "Luz verde de visión nocturna", en: "Night vision green glow" },
        ],
    },
    {
        id: 'cameraAngle',
        label: 'cameraAngle',
        singleSelect: true,
        initialVisible: 6,
        optionsPool: [
            { es: "Punto de Vista (POV)", en: "Point-of-view (POV)" },
            { es: "Plano Contrapicado", en: "Low-angle shot" },
            { es: "Plano General Amplio", en: "Wide shot" },
            { es: "Primerísimo Plano", en: "Extreme close-up" },
            { es: "Cámara en Mano/Inestable", en: "Handheld/shaky cam" },
            { es: "Plano Cenital", en: "Overhead shot" },
            { es: "Plano Holandés", en: "Dutch angle" },
            { es: "Desde Atrás", en: "Shot from behind" },
            { es: "Selfie", en: "Selfie" },
            { es: "Plano Medio", en: "Medium shot" },
            { es: "Por encima del hombro", en: "Over the shoulder shot" },
            { es: "A través de un ojo de cerradura", en: "Through a keyhole" },
            { es: "Plano Detalle", en: "Detail shot" },
            { es: "Cámara a nivel del suelo", en: "Ground-level shot" },
            { es: "Plano Americano", en: "American shot" },
            { es: "Reflejo", en: "Reflection shot" },
            { es: "Ojo de Pez", en: "Fisheye lens" },
            { es: "Fotografía Macro", en: "Macro photography" },
            { es: "Plano Aéreo", en: "Aerial shot" },
            { es: "Cámara Lenta", en: "Slow motion" },
            { es: "Plano Nadir (desde abajo)", en: "Nadir shot (from directly below)" },
            { es: "Cámara Subjetiva", en: "Subjective camera" },
            { es: "Plano Secuencia", en: "Sequence shot" },
            { es: "Bullet Time (efecto Matrix)", en: "Bullet time effect" },
            { es: "Vista de Dron", en: "Drone view" },
            { es: "Cámara de Seguridad", en: "Security camera footage" },
            { es: "A través de un Vaso o Botella", en: "Shot through a glass or bottle" },
            { es: "Fotografía con Teleobjetivo", en: "Telephoto lens shot" },
            { es: "Gran Angular Extremo (distorsión)", en: "Extreme wide-angle (distortion)" },
            { es: "Plano Inserto", en: "Insert shot" },
            { es: "Zoom Rápido", en: "Whip zoom" },
            { es: "Cámara Montada en el Cuerpo", en: "Body-mounted camera" },
            { es: "Plano sobre el Agua", en: "Over-under water shot" },
            { es: "Desde Dentro de una Boca", en: "Shot from inside a mouth" },
            { es: "Fotografía Cenital con el Sujeto Tumbado", en: "Top-down shot of subject lying down" },
            { es: "GoPro montada en un dildo", en: "GoPro mounted on a dildo" },
            { es: "Vista desde dentro de un gloryhole", en: "View from inside a gloryhole" },
            { es: "Grabación de cámara espía oculta", en: "Hidden spy cam footage" },
            { es: "Plano bajo la falda", en: "Upskirt shot" },
            { es: "Cámara endoscópica", en: "Endoscopic camera view" },
        ],
    },
    {
        id: 'style',
        label: 'style',
        singleSelect: true,
        initialVisible: 6,
        excludeFromRandom: true,
        optionsPool: [
             { es: "Fotorrealista", en: "photorealistic" },
             { es: "Hiperrealista", en: "hyperrealistic, 8k" },
             { es: "Cinematográfico", en: "cinematic, film grain" },
             { es: "Fantasía Oscura", en: "dark fantasy" },
             { es: "Ciberpunk", en: "cyberpunk, neon lighting" },
             { es: "Vaporwave", en: "vaporwave aesthetic" },
             { es: "Steampunk", en: "steampunk" },
             { es: "Blanco y Negro", en: "black and white photo" },
             { es: "Polaroid", en: "polaroid photo" },
             { es: "Vintage", en: "vintage photo" },
             { es: "Gótico", en: "gothic" },
             { es: "Arte Digital", en: "digital art" },
             { es: "Estilo Anime", en: "anime style" },
             { es: "Pintura al Óleo", en: "oil painting" },
             { es: "Arte Conceptual", en: "concept art" },
             { es: "Surrealista", en: "surreal" },
             { es: "Impresionista", en: "impressionistic" },
             { es: "Glitch Art", en: "glitch art" },
             { es: "Estilo Cómic", en: "comic book style" },
             { es: "Doble Exposición", en: "double exposure" },
             { es: "Estilo de H.R. Giger", en: "in the style of H.R. Giger, biomechanical" },
             { es: "Estilo de Caravaggio (claroscuro)", en: "in the style of Caravaggio, chiaroscuro" },
             { es: "Estilo de Manara (cómic erótico)", en: "in the style of Milo Manara, erotic comic art" },
             { es: "Estilo de Hajime Sorayama (aerografía)", en: "in the style of Hajime Sorayama, airbrush art" },
             { es: "Estilo de Luis Royo (fantasía)", en: "in the style of Luis Royo, fantasy art" },
             { es: "Renderizado de Octane", en: "Octane render" },
             { es: "Estilo de los 90 (grunge)", en: "90s grunge aesthetic" },
             { es: "Película de Terror Encontrada", en: "found footage horror film style" },
             { es: "Estilo de Videoclip de los 80", en: "80s music video style" },
             { es: "Barroco", en: "Baroque" },
             { es: "Art Nouveau", en: "Art Nouveau" },
             { es: "Pintura Prerrafaelita", en: "Pre-Raphaelite painting" },
             { es: "Fotografía de Moda de Alta Costura", en: "haute couture fashion photography" },
             { es: "Infografía Térmica", en: "thermal imaging" },
             { es: "Daguerrotipo", en: "daguerreotype" },
             { es: "Estilo de fotografía forense", en: "Forensic photography style" },
             { es: "Capturado en una webcam barata", en: "Captured on a cheap webcam" },
             { es: "Grabación de bodycam", en: "Bodycam footage" },
             { es: "Estilo de película de terror japonesa (J-horror)", en: "J-horror film style" },
             { es: "Estilo de David Lynch", en: "Lynchian, surreal horror" },
        ]
    },
    SPECIFIC_FETISHES_CATEGORY_CONFIG,
    EXTRA_PEOPLE_CATEGORY_CONFIG
];

export const INFINITE_PROMPT_IDEAS: PromptOption[] = [
  { es: "Recompensa Facial Bukkake", en: "Bukkake Facial Reward" },
  { es: "Insinuación de Micción Pública", en: "Public Urination Tease" },
  { es: "Gangbang de Creampie Anal", en: "Anal Creampie Gangbang" },
  { es: "Sorpresa en Gloryhole", en: "Gloryhole Slut Surprise" },
  { es: "Degradación con Juego de Mascotas BDSM", en: "BDSM Pet Play Degradation" },
  { es: "Maratón de Orgasmos Forzados", en: "Forced Orgasm Marathon" },
  { es: "Sobrecarga de Doble Penetración", en: "Double Penetration Overload" },
  { es: "Diosa Bebedora de Orina", en: "Piss-Drinking Goddess" },
  { es: "Sumisión con Juego de Heces", en: "Scat Play Submission" },
  { es: "Puta Drogada y Usada", en: "Drugged and Used Slut" },
  { es: "Sexo Público en Callejón", en: "Public Sex in Alleyway" },
  { es: "Dominación Lésbica con Strap-On", en: "Lesbian Strap-On Domination" },
  { es: "Ruptura Mental y Lavado de Cerebro", en: "Mind Break & Brainwashing" },
  { es: "Exhibicionista en Biblioteca", en: "Exhibitionist Flash in Library" },
  { es: "Entrenamiento de Garganta Profunda Extrema", en: "Extreme Deepthroat Training" },
  { es: "Novatada de Gangbang en Hermandad", en: "Sorority Gangbang Hazing" },
  { es: "Juego de Rol de Interrogatorio Nazi", en: "Nazi Interrogation Roleplay" },
  { es: "Abducción y Sondeo Alienígena", en: "Alien Abduction & Probing" },
  { es: "Escenario de Sexo con Monstruos", en: "Monster Fucking Scenario" },
  { es: "Mensaje de Voz de tu Acosador", en: "Voicemail from your Stalker" },
  { es: "Pillada Masturbándose por Papá", en: "Caught Masturbating by Dad" },
  { es: "Chantajeada para ser un Contenedor de Semen", en: "Blackmailed into being a Cumdump" },
  { es: "Juego de Rol de Secuestro y Violación", en: "CNC Kidnapping" },
  { es: "Entrenamiento de 'Pony Play'", en: "Pony Play Training" },
  { es: "Servicio de Inodoro Humano", en: "Human Toilet Service" },
  { es: "Engañando al Marido", en: "Cheating on Husband" },
  { es: "Fantasía de Corrupción de Monja", en: "Nun Corruption Fantasy" },
  { es: "Manoseo en Transporte Público", en: "Public Transport Groping" },
  { es: "Reto de 'Spitroast'", en: "Spitroast Challenge" },
  { es: "Blanco de Corrida Facial Ahegao", en: "Ahegao Face Cum Target" },
  { es: "Escritura Corporal y Degradación", en: "Bodywriting & Degradation" },
  { es: "Juego de Cerdos / Fetiche de Barro", en: "Pig Play / Mud Fetish" },
  { es: "Adoración de 'Size Queen'", en: "Size Queen Worship" },
  { es: "Máquina Sexual Robótica", en: "Robot Fucking Machine" },
  { es: "Puta Familiar de Uso Libre", en: "Free Use Family Slut" },
  { es: "Subasta de Esclavos 'Raceplay'", en: "Raceplay Slave Auction" },
  { es: "Juego de Rol de Víctima de Película 'Snuff'", en: "Snuff Film Victim Roleplay" },
  { es: "Orgia Gangbang de Payasos", en: "Clown Gangbang Orgy" },
  { es: "Fantasía de Contenedor de Semen Indigente", en: "Homeless Cumdump Fantasy" },
  { es: "Cría en Apocalipsis Zombi", en: "Zombie Apocalypse Breeding" },
  { es: "Juego con Vómito / Emetofilia", en: "Vomit / Emetophilia Play" },
  { es: "Transformación en Muñeca Inanimada", en: "Inanimate Doll Transformation" },
  { es: "Ruleta de 'Bug Chasing'", en: "Bug Chasing Roulette" },
  { es: "Escenario de 'Ageplay' Extremo", en: "Extreme Ageplay Scenario" },
  { es: "Ritual de Profanación Religiosa", en: "Religious Defilement Ritual" },
  { es: "Audición para Película Snuff (CNC)", en: "Snuff Film Audition (CNC)" },
  { es: "Entrenamiento de Esclava de Control Mental", en: "Mind Control Slave Training" },
  { es: "Examen Ginecológico Extremo", en: "Extreme Gynecological Examination" },
  { es: "Degradación en Granja de Animales", en: "Animal Farm Degradation" },
  { es: "Juego de Rol de Violación Correctiva", en: "Corrective Rape Roleplay" },
  { es: "Transformación en Objeto Inanimado", en: "Inanimate Object Transformation" },
  { es: "Fiesta de Vómito y Emetofilia", en: "Vomit and Emetophilia Party" },
  { es: "Humillación con Comida (Slopping)", en: "Food Humiliation (Slopping)" },
  { es: "Esclava de Ordeño Humano", en: "Human Milking Cow Slave" },
  { es: "Adoración de Muñones (Acrotomofilia)", en: "Stump Worship (Acrotophilia)" },
  { es: "Consumo de Fluidos Corporales", en: "Bodily Fluid Consumption" },
  { es: "Abuso en Secta Religiosa", en: "Religious Cult Abuse" },
  { es: "Objeto Sexual de Uso Libre Familiar", en: "Free-Use Family Sex Object" },
  { es: "Exhibicionismo y Masturbación en Grupo", en: "Group Masturbation Exhibitionism" },
  { es: "Fiesta de Sexo con Payasos (Coulrofilia)", en: "Clown Sex Party (Coulrophilia)" },
  { es: "Fetiche de Gases y Flatulencia", en: "Gas and Flatulence Fetish" },
  { es: "Violación por Tentáculos en Laboratorio", en: "Laboratory Tentacle Rape" },
  { es: "Humillación por Pechos Pequeños", en: "Small Tits Humiliation" },
  { es: "Juego de Rol de Violación por Figuras de Autoridad", en: "Authority Figure Rape Roleplay" },
  { es: "Corrupción de la Inocencia y 'Ageplay'", en: "Innocence Corruption and Ageplay" },
  { es: "Degradación como Cenicienta Esclava", en: "Cinderella Slave Degradation" },
];